### ISSUE TITLE
Paginating relatedQuery results

### ISSUE THREAD

**Issue by mstaniewski** [Vincit/objection.js#887] opened 2018-04-23 13:23 UTC
Hello,

I've ManyToManyRelation defined on my User Model, which looks like following: 
```
favourites: {
      relation: Model.ManyToManyRelation,
      modelClass: `${__dirname}/Attraction`,
      join: {
        from: 'attractions.id',
        through: {
          from: 'users_favourites.user_id',
          to: 'users_favourites.attraction_id',
        },
        to: 'users.id',
      },
    },
```

How do i actually fetch favourites of user and paginate them?

Tried something like this:

```
const user = await User
      .query()
      .findById(user_id)

const favourites = await user
      .$relatedQuery('favourites')
      .page(page, pageSize)
    
console.log(favourites)
```

But actually it doesn't return any results for given query:
`{ results: [], total: 1 }`

Any simple solution for this?

Thanks for help :)

**Comment by mstaniewski** [comment] 2018-04-23 19:41
Yes, page is actually 0

**Comment by koskimas** [comment] 2018-04-23 19:50
The following example works. You can just put that in a file and run it. Could you modify it so that your issue is reproduced?

```js
/**
 * This is a simple template for bug reproductions. It contains three models `Person`, `Animal` and `Movie`.
 * They create a simple IMDB-style database. Try to add minimal modifications to this file to reproduce
 * your bug.
 *
 * install:
 *    npm install objection knex sqlite3 chai
 *
 * run:
 *    node reproduction-template
 */

let Model;

try {
  Model = require('./').Model;
} catch (err) {
  Model = require('objection').Model;
}

const Knex = require('knex');
const chai = require('chai');

async function main() {
  await createSchema();

  ///////////////////////////////////////////////////////////////
  // Your reproduction
  ///////////////////////////////////////////////////////////////

  await Person.query().insertGraph({
    firstName: 'Jennifer',
    lastName: 'Lawrence',

    pets: [
      {
        name: 'Doggo',
        species: 'dog'
      }
    ],

    movies: [
      {
        name: 'Movie 1'
      },
      {
        name: 'Movie 2'
      }
    ]
  });

  const jennifer = await Person.query()
    .findOne({ firstName: 'Jennifer' })

  const movies = await jennifer.$relatedQuery('movies').page(0, 1);
  console.log(movies);
}

///////////////////////////////////////////////////////////////
// Database
///////////////////////////////////////////////////////////////

const knex = Knex({
  client: 'sqlite3',
  useNullAsDefault: true,
  connection: {
    filename: ':memory:'
  }
});

Model.knex(knex);

///////////////////////////////////////////////////////////////
// Models
///////////////////////////////////////////////////////////////

class Person extends Model {
  static get tableName() {
    return 'Person';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['firstName', 'lastName'],

      properties: {
        id: { type: 'integer' },
        parentId: { type: ['integer', 'null'] },
        firstName: { type: 'string', minLength: 1, maxLength: 255 },
        lastName: { type: 'string', minLength: 1, maxLength: 255 },
        age: { type: 'number' },

        address: {
          type: 'object',
          properties: {
            street: { type: 'string' },
            city: { type: 'string' },
            zipCode: { type: 'string' }
          }
        }
      }
    };
  }

  static get relationMappings() {
    return {
      pets: {
        relation: Model.HasManyRelation,
        modelClass: Animal,
        join: {
          from: 'Person.id',
          to: 'Animal.ownerId'
        }
      },

      movies: {
        relation: Model.ManyToManyRelation,
        modelClass: Movie,
        join: {
          from: 'Person.id',
          through: {
            from: 'Person_Movie.personId',
            to: 'Person_Movie.movieId'
          },
          to: 'Movie.id'
        }
      },

      children: {
        relation: Model.HasManyRelation,
        modelClass: Person,
        join: {
          from: 'Person.id',
          to: 'Person.parentId'
        }
      },

      parent: {
        relation: Model.BelongsToOneRelation,
        modelClass: Person,
        join: {
          from: 'Person.parentId',
          to: 'Person.id'
        }
      }
    };
  }
}

class Animal extends Model {
  static get tableName() {
    return 'Animal';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],

      properties: {
        id: { type: 'integer' },
        ownerId: { type: ['integer', 'null'] },
        name: { type: 'string', minLength: 1, maxLength: 255 },
        species: { type: 'string', minLength: 1, maxLength: 255 }
      }
    };
  }

  static get relationMappings() {
    return {
      owner: {
        relation: Model.BelongsToOneRelation,
        modelClass: Person,
        join: {
          from: 'Animal.ownerId',
          to: 'Person.id'
        }
      }
    };
  }
}

class Movie extends Model {
  static get tableName() {
    return 'Movie';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],

      properties: {
        id: { type: 'integer' },
        name: { type: 'string', minLength: 1, maxLength: 255 }
      }
    };
  }

  static get relationMappings() {
    return {
      actors: {
        relation: Model.ManyToManyRelation,
        modelClass: Person,
        join: {
          from: 'Movie.id',
          through: {
            from: 'Person_Movie.movieId',
            to: 'Person_Movie.personId'
          },
          to: 'Person.id'
        }
      }
    };
  }
}

///////////////////////////////////////////////////////////////
// Schema
///////////////////////////////////////////////////////////////

async function createSchema() {
  await knex.schema
    .dropTableIfExists('Person_Movie')
    .dropTableIfExists('Animal')
    .dropTableIfExists('Movie')
    .dropTableIfExists('Person');

  await knex.schema
    .createTable('Person', table => {
      table.increments('id').primary();
      table
        .integer('parentId')
        .unsigned()
        .references('id')
        .inTable('Person');
      table.string('firstName');
      table.string('lastName');
      table.integer('age');
      table.json('address');
    })
    .createTable('Movie', table => {
      table.increments('id').primary();
      table.string('name');
    })
    .createTable('Animal', table => {
      table.increments('id').primary();
      table
        .integer('ownerId')
        .unsigned()
        .references('id')
        .inTable('Person');
      table.string('name');
      table.string('species');
    })
    .createTable('Person_Movie', table => {
      table.increments('id').primary();
      table
        .integer('personId')
        .unsigned()
        .references('id')
        .inTable('Person')
        .onDelete('CASCADE');
      table
        .integer('movieId')
        .unsigned()
        .references('id')
        .inTable('Movie')
        .onDelete('CASCADE');
    });
}

main()
  .then(() => console.log('success'))
  .catch(console.error);
```

**Comment by koskimas** [comment] 2018-04-24 18:49
I'll close this for now since there seems to be no answer. I'll reopen this if you can reproduce the problem using the code I posted (or any other way).

**Closed by koskimas** 2018-04-24 18:49 UTC
Labels: needs more info

**Comment by molaeiali** [comment] 2021-11-14 08:43
> The following example works. You can just put that in a file and run it. Could you modify it so that your issue is reproduced?
> 
> ```js
> /**
>  * This is a simple template for bug reproductions. It contains three models `Person`, `Animal` and `Movie`.
>  * They create a simple IMDB-style database. Try to add minimal modifications to this file to reproduce
>  * your bug.
>  *
>  * install:
>  *    npm install objection knex sqlite3 chai
>  *
>  * run:
>  *    node reproduction-template
>  */
> 
> let Model;
> 
> try {
>   Model = require('./').Model;
> } catch (err) {
>   Model = require('objection').Model;
> }
> 
> const Knex = require('knex');
> const chai = require('chai');
> 
> async function main() {
>   await createSchema();
> 
>   ///////////////////////////////////////////////////////////////
>   // Your reproduction
>   ///////////////////////////////////////////////////////////////
> 
>   await Person.query().insertGraph({
>     firstName: 'Jennifer',
>     lastName: 'Lawrence',
> 
>     pets: [
>       {
>         name: 'Doggo',
>         species: 'dog'
>       }
>     ],
> 
>     movies: [
>       {
>         name: 'Movie 1'
>       },
>       {
>         name: 'Movie 2'
>       }
>     ]
>   });
> 
>   const jennifer = await Person.query()
>     .findOne({ firstName: 'Jennifer' })
> 
>   const movies = await jennifer.$relatedQuery('movies').page(0, 1);
>   console.log(movies);
> }
> 
> ///////////////////////////////////////////////////////////////
> // Database
> ///////////////////////////////////////////////////////////////
> 
> const knex = Knex({
>   client: 'sqlite3',
>   useNullAsDefault: true,
>   connection: {
>     filename: ':memory:'
>   }
> });
> 
> Model.knex(knex);
> 
> ///////////////////////////////////////////////////////////////
> // Models
> ///////////////////////////////////////////////////////////////
> 
> class Person extends Model {
>   static get tableName() {
>     return 'Person';
>   }
> 
>   static get jsonSchema() {
>     return {
>       type: 'object',
>       required: ['firstName', 'lastName'],
> 
>       properties: {
>         id: { type: 'integer' },
>         parentId: { type: ['integer', 'null'] },
>         firstName: { type: 'string', minLength: 1, maxLength: 255 },
>         lastName: { type: 'string', minLength: 1, maxLength: 255 },
>         age: { type: 'number' },
> 
>         address: {
>           type: 'object',
>           properties: {
>             street: { type: 'string' },
>             city: { type: 'string' },
>             zipCode: { type: 'string' }
>           }
>         }
>       }
>     };
>   }
> 
>   static get relationMappings() {
>     return {
>       pets: {
>         relation: Model.HasManyRelation,
>         modelClass: Animal,
>         join: {
>           from: 'Person.id',
>           to: 'Animal.ownerId'
>         }
>       },
> 
>       movies: {
>         relation: Model.ManyToManyRelation,
>         modelClass: Movie,
>         join: {
>           from: 'Person.id',
>           through: {
>             from: 'Person_Movie.personId',
>             to: 'Person_Movie.movieId'
>           },
>           to: 'Movie.id'
>         }
>       },
> 
>       children: {
>         relation: Model.HasManyRelation,
>         modelClass: Person,
>         join: {
>           from: 'Person.id',
>           to: 'Person.parentId'
>         }
>       },
> 
>       parent: {
>         relation: Model.BelongsToOneRelation,
>         modelClass: Person,
>         join: {
>           from: 'Person.parentId',
>           to: 'Person.id'
>         }
>       }
>     };
>   }
> }
> 
> class Animal extends Model {
>   static get tableName() {
>     return 'Animal';
>   }
> 
>   static get jsonSchema() {
>     return {
>       type: 'object',
>       required: ['name'],
> 
>       properties: {
>         id: { type: 'integer' },
>         ownerId: { type: ['integer', 'null'] },
>         name: { type: 'string', minLength: 1, maxLength: 255 },
>         species: { type: 'string', minLength: 1, maxLength: 255 }
>       }
>     };
>   }
> 
>   static get relationMappings() {
>     return {
>       owner: {
>         relation: Model.BelongsToOneRelation,
>         modelClass: Person,
>         join: {
>           from: 'Animal.ownerId',
>           to: 'Person.id'
>         }
>       }
>     };
>   }
> }
> 
> class Movie extends Model {
>   static get tableName() {
>     return 'Movie';
>   }
> 
>   static get jsonSchema() {
>     return {
>       type: 'object',
>       required: ['name'],
> 
>       properties: {
>         id: { type: 'integer' },
>         name: { type: 'string', minLength: 1, maxLength: 255 }
>       }
>     };
>   }
> 
>   static get relationMappings() {
>     return {
>       actors: {
>         relation: Model.ManyToManyRelation,
>         modelClass: Person,
>         join: {
>           from: 'Movie.id',
>           through: {
>             from: 'Person_Movie.movieId',
>             to: 'Person_Movie.personId'
>           },
>           to: 'Person.id'
>         }
>       }
>     };
>   }
> }
> 
> ///////////////////////////////////////////////////////////////
> // Schema
> ///////////////////////////////////////////////////////////////
> 
> async function createSchema() {
>   await knex.schema
>     .dropTableIfExists('Person_Movie')
>     .dropTableIfExists('Animal')
>     .dropTableIfExists('Movie')
>     .dropTableIfExists('Person');
> 
>   await knex.schema
>     .createTable('Person', table => {
>       table.increments('id').primary();
>       table
>         .integer('parentId')
>         .unsigned()
>         .references('id')
>         .inTable('Person');
>       table.string('firstName');
>       table.string('lastName');
>       table.integer('age');
>       table.json('address');
>     })
>     .createTable('Movie', table => {
>       table.increments('id').primary();
>       table.string('name');
>     })
>     .createTable('Animal', table => {
>       table.increments('id').primary();
>       table
>         .integer('ownerId')
>         .unsigned()
>         .references('id')
>         .inTable('Person');
>       table.string('name');
>       table.string('species');
>     })
>     .createTable('Person_Movie', table => {
>       table.increments('id').primary();
>       table
>         .integer('personId')
>         .unsigned()
>         .references('id')
>         .inTable('Person')
>         .onDelete('CASCADE');
>       table
>         .integer('movieId')
>         .unsigned()
>         .references('id')
>         .inTable('Movie')
>         .onDelete('CASCADE');
>     });
> }
> 
> main()
>   .then(() => console.log('success'))
>   .catch(console.error);
> ```

just change line 55 to
```
const movies = await Person.query().withGraphJoined('movies').page(0, 10);
```
If you want to get all Persons with joined movies, you will get one person, but the total is 2.
```
{
  results: [
    Person {
      id: 1,
      parentId: null,
      firstName: 'Jennifer',
      lastName: 'Lawrence',
      age: null,
      address: null,
      movies: [Array]
    }
  ],
  total: 2
}
```
It is counting returned joined records from the database, which are two (because there are two movies, so when we join person with movies, we get two rows, but they have the same person Id, and I queried for person, so I should get one person, and I am, but the total should be 1.

I'm having this issue with
```
    "chai": "^4.3.4",
    "knex": "^0.95.14",
    "objection": "^3.0.0",
    "sqlite3": "^5.0.2"
```

and also in:
```
    "knex": "^0.21.19",
    "objection": "^2.2.15",
```

**Comment by molaeiali** [comment] 2021-11-14 08:43
> I'll close this for now since there seems to be no answer. I'll reopen this if you can reproduce the problem using the code I posted (or any other way).

Can you reopen this issue? or guide me to a solution? thanks

**Comment by koskimas** [comment] 2021-11-14 09:30
@molaeiali Your example has nothing to do with this issue.

**Comment by molaeiali** [comment] 2021-11-14 09:36
> @molaeiali Your example has nothing to do with this issue.
Oh, I see, my problem is in reverse I think, should I open another issue then? or I am doing something wrong?
