### ISSUE TITLE
Typescript TS2694 tsc errors 

### ISSUE THREAD

**Issue by vladaman** [Vincit/objection.js#2017] opened 2021-03-13 06:06 UTC
Hi,

I am getting following errors when running `tsc src/app.ts`

```
node_modules/objection/typings/objection/index.d.ts:120:32 - error TS2694: Namespace '"/home/vlad/tmp/nodejs-knex-orm/node_modules/knex/types/index"' has no exported member 'Raw'.

120   type Raw = RawBuilder | Knex.Raw;
                                   ~~~

node_modules/objection/typings/objection/index.d.ts:525:49 - error TS2694: Namespace '"/home/vlad/tmp/nodejs-knex-orm/node_modules/knex/types/index"' has no exported member 'JoinClause'.

525     (table: TableRef<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;
                                                    ~~~~~~~~~~

node_modules/objection/typings/objection/index.d.ts:611:22 - error TS2694: Namespace '"/home/vlad/tmp/nodejs-knex-orm/node_modules/knex/types/index"' has no exported member 'ColumnInfo'.

611     (): Promise<Knex.ColumnInfo>;
                         ~~~~~~~~~~
```

```
tsc --version -> Version 4.2.3
node --version -> v12.20.0
npm --version -> 7.6.3
objection version -> 2.2.14
knex version -> 0.95.2
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "outDir": "build/dist"
  },
  "lib": [
    "es6"
  ],
  "exclude": [
    "node_modules",
    ".vscode",
    "build",
    "scripts",
    "obj",
    "**/*.spec.ts"
  ],
  "include": [
    "app.ts",
    "src",
    "src/**/*.ts",
    "@types/**/*.d.ts",
    "node_modules/axios",
    "node_modules/redux-thunk"
  ]
}
```

**Comment by koskimas** [comment] 2021-03-13 07:12
Duplicate of #2012

**Closed by koskimas** 2021-03-13 07:12 UTC
