### ISSUE TITLE
WithGraphFetched with composite key not working correctly

### ISSUE THREAD

**Issue by Naeoth** [Vincit/objection.js#1623] opened 2019-12-19 10:50 UTC
I'm trying to generate the model automatically from the database schema based on the `information_schema`. So I created the model of the tables that I used to retrieve all the necessary informations:

```javascript
class KeyColumnUsage extends Model {
  static get tableName() {
    return 'KEY_COLUMN_USAGE'
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: [
        'CONSTRAINT_CATALOG',
        'CONSTRAINT_SCHEMA',
        'CONSTRAINT_NAME',
        'TABLE_CATALOG',
        'TABLE_SCHEMA',
        'TABLE_NAME',
        'COLUMN_NAME',
      ],
      properties: {
        CONSTRAINT_CATALOG: { type: 'string' },
        CONSTRAINT_SCHEMA: { type: 'string' },
        CONSTRAINT_NAME: { type: 'string' },
        TABLE_CATALOG: { type: 'string' },
        TABLE_SCHEMA: { type: 'string' },
        TABLE_NAME: { type: 'string' },
        COLUMN_NAME: { type: 'string' },
        ORDINAL_POSITION: { type: 'integer' },
        POSITION_IN_UNIQUE_CONSTRAINT: { type: 'integer' },
        REFERENCED_TABLE_SCHEMA: { type: 'string' },
        REFERENCED_TABLE_NAME: { type: 'string' },
        REFERENCED_COLUMN_NAME: { type: 'string' },
      },
    }
  }
}
```
```javascript
class Columns extends Model {
  static get tableName() {
    return 'COLUMNS'
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: [
        'TABLE_CATALOG',
        'TABLE_SCHEMA',
        'TABLE_NAME',
        'COLUMN_NAME',
        'IS_NULLABLE',
        'DATA_TYPE',
        'COLUMN_TYPE',
        'COLUMN_KEY',
        'EXTRA',
        'PRIVILEGES',
        'COLUMN_COMMENT',
      ],
      properties: {
        TABLE_CATALOG: { type: 'string' },
        TABLE_SCHEMA: { type: 'string' },
        TABLE_NAME: { type: 'string' },
        COLUMN_NAME: { type: 'string' },
        ORDINAL_POSITION: { type: 'integer' },
        COLUMN_DEFAULT: { type: 'string' },
        IS_NULLABLE: { type: 'string' },
        DATA_TYPE: { type: 'string' },
        CHARACTER_MAXIMUM_LENGTH: { type: 'integer' },
        CHARACTER_OCTET_LENGTH: { type: 'integer' },
        NUMERIC_PRECISION: { type: 'integer' },
        NUMERIC_SCALE: { type: 'integer' },
        DATETIME_PRECISION: { type: 'integer' },
        CHARACTER_SET_NAME: { type: 'string' },
        COLLATION_NAME: { type: 'string' },
        COLUMN_TYPE: { type: 'string' },
        COLUMN_KEY: { type: 'string' },
        EXTRA: { type: 'string' },
        PRIVILEGES: { type: 'string' },
        COLUMN_COMMENT: { type: 'string' },
      },
    }
  }

  static get relationMappings() {
    return {
      constrain: {
        relation: Model.BelongsToOneRelation,
        modelClass: KeyColumnUsage,
        filter: query => query.where('TABLE_SCHEMA', database).whereNotNull('REFERENCED_COLUMN_NAME'),
        join: {
          from: ['COLUMNS.TABLE_NAME', 'COLUMNS.COLUMN_NAME'],
          to: ['KEY_COLUMN_USAGE.TABLE_NAME', 'KEY_COLUMN_USAGE.COLUMN_NAME'],
        },
      },
    }
  }
}
```
```javascript
class Tables extends Model {
  static get tableName() {
    return 'TABLES'
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['TABLE_CATALOG', 'TABLE_SCHEMA', 'TABLE_NAME', 'TABLE_TYPE', 'TABLE_COMMENT'],
      properties: {
        TABLE_CATALOG: { type: 'string' },
        TABLE_SCHEMA: { type: 'string' },
        TABLE_NAME: { type: 'string' },
        TABLE_TYPE: { type: 'string' },
        ENGINE: { type: 'string' },
        VERSION: { type: 'integer' },
        ROW_FORMAT: { type: 'string' },
        TABLE_ROWS: { type: 'integer' },
        AVG_ROW_LENGTH: { type: 'integer' },
        DATA_LENGTH: { type: 'integer' },
        MAX_DATA_LENGTH: { type: 'integer' },
        INDEX_LENGTH: { type: 'integer' },
        DATA_FREE: { type: 'integer' },
        AUTO_INCREMENT: { type: 'integer' },
        CREATE_TIME: { type: 'date-time' },
        UPDATE_TIME: { type: 'date-time' },
        CHECK_TIME: { type: 'date-time' },
        TABLE_COLLATION: { type: 'string' },
        CHECKSUM: { type: 'integer' },
        CREATE_OPTIONS: { type: 'string' },
        TABLE_COMMENT: { type: 'string' },
      },
    }
  }
```

As you can see, I have a composite key between `COLUMNS` and  `KEY_COLUMN_USAGE` on the column name and the table name. When I try to find all the contrains from all the columns with `withGraphFetched`, I always get `null`.

The query:
```javascript
await Columns.query().withGraphFetched('constrain')
```

But when I use a where condition, I can get the right constrain:
```javascript
await Columns.query()
    .where({
      TABLE_NAME: 'persons',
      COLUMN_NAME: pets',
    })
    .withGraphFetched('constrain')
```

My goal is to call this query to have all the information about my schema:
```javascript
await Tables.query()
    .where('table_schema', 'my_database_name)
    .withGraphFetched('columns.constrain')
```

**Comment by koskimas** [comment] 2019-12-19 12:57
Objection has tests for this type of setup with composite keys and they all pass. I'll need an actual reproduction or I can't help you.

**Comment by koskimas** [comment] 2019-12-19 13:58
At least it seems that you haven't specified `idColumn` for your models. The default is lowercase `id`. I'm quessing those tables have a different primary key.

**Comment by Naeoth** [comment] 2019-12-19 14:41
Thanks for you reply, indeed the `information_schema` doesn't seem to have `id` neither a primary key: https://mariadb.com/kb/en/library/information-schema-key_column_usage-table/ (I use mariaDB).

I tested with the same tables that the objection website provides for its example, but the `information_schema` has not been updated automatically. I don't know how and when it is done by the database. But I have the information for my other tables I created few months ago. If you do a ```SELECT * FROM information_schema.COLUMNS``` you should be able to see all your columns schema. At least if you have one foreign key, you will be in the same case, for example:

```javascript
async function createSchema() {
  if (!(await knex.schema.hasTable('pets'))) {
    await knex.schema.createTable('pets', table => {
      table.increments('id').primary()
      table.string('name')
    })
  }

  if (!(await knex.schema.hasTable('persons'))) {
    await knex.schema.createTable('persons', table => {
      table.increments('id').primary()
      table.string('firstname')
      table.integer('pet_id').references('pets.id')
    })
  }
}
```
```javascript
class Pet extends Model {
  static get tableName() {
    return 'pets'
  }
}
```
```javascript
class Person extends Model {
  static get tableName() {
    return 'persons'
  }

  static get relationMappings() {
    return {
      pet: {
        relation: Model.BelongsToOneRelation,
        modelClass: Pet,
        join: {
          from: 'persons.pet_id',
          to: 'pets.id',
        },
      },
    }
  }
}
```

**Comment by koskimas** [comment] 2019-12-19 16:58
Sorry, but I don't have time to write a test for your case myself. I need a full reproduction I can run using a single command, like `node your-script.js`. 95% of these are user errors caused by some mistake in the setup. If I spend an hour or so writing tests for each issue, it would take up all my time and 95% of that time goes to waste. I'm happy to debug your code if you provide a failing example, but until that I can't help. I'm closing this now, but feel free to provide the repro and I'll take a look.

**Comment by koskimas** [comment] 2019-12-19 19:45
You don't need to use the actual information schema tables in the repro. Objection doesn't know or care what the tables are. You can create similar tables with similar compound keys in the repro and reproduce the issue using those.

**Comment by Naeoth** [comment] 2019-12-20 16:51
Ok, I change few things based on what you said. This is a complete example in ES6 of what I'm trying to do and the problems are displayed in the console:

```javascript
import Knex from 'knex'
import { Model } from 'objection'

// Database name
const options = {
  host: 'localhost',
  user: 'root',
  password: 'pwd',
}

const db = Knex({
  client: 'mysql',
  connection: {
    ...options,
    database: 'dev', // Database name to test
  },
})

const knex = Knex({
  client: 'mysql',
  connection: {
    ...options,
    database: 'information_schema',
  },
})

Model.knex(knex)

class Pet extends Model {
  static get tableName() {
    return 'pets'
  }
}

class Person extends Model {
  static get tableName() {
    return 'persons'
  }

  static get relationMappings() {
    return {
      pet: {
        relation: Model.BelongsToOneRelation,
        modelClass: Pet,
        join: {
          from: 'persons.pet_id',
          to: 'pets.id',
        },
      },
    }
  }
}

class KeyColumnUsage extends Model {
  static get tableName() {
    return 'KEY_COLUMN_USAGE'
  }

  static get idColumn() {
    return ['TABLE_NAME', 'COLUMN_NAME']
  }
}

class Columns extends Model {
  static get tableName() {
    return 'COLUMNS'
  }

  static get idColumn() {
    return ['TABLE_NAME', 'COLUMN_NAME']
  }

  static get relationMappings() {
    return {
      constrain: {
        relation: Model.BelongsToOneRelation,
        modelClass: KeyColumnUsage,
        filter: query => query.where('TABLE_SCHEMA', db.client.database()).whereNotNull('REFERENCED_COLUMN_NAME'),
        join: {
          from: ['COLUMNS.TABLE_NAME', 'COLUMNS.COLUMN_NAME'],
          to: ['KEY_COLUMN_USAGE.TABLE_NAME', 'KEY_COLUMN_USAGE.COLUMN_NAME'],
        },
      },
    }
  }
}

class Tables extends Model {
  static get tableName() {
    return 'TABLES'
  }

  static get relationMappings() {
    return {
      columns: {
        relation: Model.HasManyRelation,
        modelClass: Columns,
        filter: query => query.where('TABLE_SCHEMA', db.client.database()),
        join: { from: 'TABLES.TABLE_NAME', to: 'COLUMNS.TABLE_NAME' },
      },
    }
  }
}

async function createSchema() {
  if (!(await db.schema.hasTable('pets'))) {
    await db.schema.createTable('pets', table => {
      table.increments('id').primary()
      table.string('name').notNullable()
    })
  }

  if (!(await db.schema.hasTable('persons'))) {
    await db.schema.createTable('persons', table => {
      table.increments('id').primary()
      table.string('firstname').notNullable()
      table
        .integer('pet_id')
        .unsigned()
        .notNullable()
      table.foreign('pet_id').references('pets.id')
    })
  }
}

;(async () => {
  await createSchema()

  const keyColumn = await KeyColumnUsage.query().where({
    TABLE_NAME: 'persons',
    COLUMN_NAME: 'pet_id',
  })

  // Check that the constrain exist
  console.log('"pet_id" constrain:', keyColumn)

  const column = await Columns.query()
    .where({
      TABLE_NAME: 'persons',
      COLUMN_NAME: 'pet_id',
    })
    .withGraphFetched('constrain')

  // Check that the constrain exist on the specified column
  console.log('"pet_id" column:', column)

  const columns = await Columns.query()
    .withGraphFetched('constrain')
    .where({ TABLE_SCHEMA: db.client.database() })

  // Constrain is not auto filled by the withGraphFetched
  console.log('All columns:', columns)

  const tables = await Tables.query()
    .where({
      TABLE_SCHEMA: db.client.database(),
      TABLE_NAME: 'persons',
    })
    .withGraphFetched('columns.constrain')
    .first()

  // Constrain is always null and should be auto filled by the withGraphFetched thanks to the composite keys
  console.log('"persons" columns:', tables.columns)

  process.exit()
})()
```

**Comment by koskimas** [comment] 2019-12-20 18:41
Perfect, thanks for the script! I'll take a look at this soon.

**Comment by koskimas** [comment] 2019-12-23 11:12
I don't undestand what's going on here, but it doesn't seem to be related to objection. Objection generates the correct query (that has multiple tests), but for some reason, the information schema database only returns values when there's one single item in a composite `WHERE IN` list. You can reproduce the bug without objection by running this query

```js
  const result = await knex.raw([
    "select `KEY_COLUMN_USAGE`.*",
    "from `KEY_COLUMN_USAGE`",
    "where (`KEY_COLUMN_USAGE`.`TABLE_NAME`, `KEY_COLUMN_USAGE`.`COLUMN_NAME`)",
    "in (('persons', 'pet_id'), ('persons', 'id'))"
  ].join(' '))

  console.log(result[0])
```

The above query doesn't return any results. But when the second item in the list is removed, we do get a result

```js
  const result = await knex.raw([
    "select `KEY_COLUMN_USAGE`.*",
    "from `KEY_COLUMN_USAGE`",
    "where (`KEY_COLUMN_USAGE`.`TABLE_NAME`, `KEY_COLUMN_USAGE`.`COLUMN_NAME`)",
    "in (('persons', 'pet_id'))"
  ].join(' '))

  console.log(result[0])
```

This could somehow be a knex bug, but I doubt it too.

**Closed by koskimas** 2019-12-23 11:12 UTC

**Comment by koskimas** [comment] 2019-12-23 11:25
You can work around this using `withGraphFetched('constrain', { maxBatchSize: 1 })` which forces the `where in` list to have one value, but it makes the queries much slower in some cases. You should be fine in this case though. I don't think you'll have thousands of tables and columns.
