### ISSUE TITLE
RangeError: Maximum call stack size exceeded at recursiveTypeRelatedTo after upgrading to 3.0

### ISSUE THREAD

**Issue by hkjeffchan** [Vincit/objection.js#2178] opened 2021-12-20 14:10 UTC
```typescript
import { Model, RelationMappings, RelationMappingsThunk } from 'objection';

export class BaseModel extends Model {
  id: number;

  static get modelPaths() {
    return [__dirname];
  }
}

export class Product extends BaseModel {
  static tableName = 'product';
  price: number;
  user?: User;

  static relationMappings: RelationMappings | RelationMappingsThunk = {
    productList: {
      relation: Model.BelongsToOneRelation,
      modelClass: 'User',
      join: {
        from: 'product.userId',
        to: 'user.id',
      },
    },
  };
}

export class User extends BaseModel {
  static tableName = 'user';
  name: string;
  // productList?: Product;

  static relationMappings: RelationMappings | RelationMappingsThunk = {
    productList: {
      relation: Model.HasManyRelation,
      modelClass: 'Product',
      join: {
        from: 'user.id',
        to: 'product.userId',
      },
    },
  };
}
```
If I uncomment the line "productList?: Product", I got the following error:
RangeError: Maximum call stack size exceeded
    at recursiveTypeRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63793:44)
    at isRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63388:30)
    at typeRelatedToSomeType (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63654:35)
    at structuredTypeRelatedToWorker (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63926:32)
    at structuredTypeRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63908:30)
    at isRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63385:30)
    at checkTypeRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:63003:26)
    at isTypeRelatedTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:62954:24)
    at isTypeAssignableTo (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:62160:20)
    at getConditionalType (/Applications/MAMP/htdocs/test-obj3/node_modules/typescript/lib/typescript.js:60943:133)

This only happens after upgrading to objection@3.0.0. This is fine in 2.x.

Already set tsconfig to 
"strict": true,

Seems related to
https://github.com/microsoft/TypeScript/issues/33460

**Comment by hkjeffchan** [comment] 2021-12-20 14:21
setting "strictNullChecks": false can fix temporarily

**Comment by koskimas** [comment] 2021-12-20 15:33
Also using `strict: true` fixes this.

**Comment by koskimas** [comment] 2021-12-20 15:35
> Already set tsconfig to
> "strict": true,

Are you sure? Your example won't compile in strict mode. `id: number;` or `name: string;` won't work in strict mode.

**Comment by sjinks** [comment] 2021-12-20 16:30
Here is a test project to reproduce the issue.

[test.zip](https://github.com/Vincit/objection.js/files/7746646/test.zip)

`npm test` fails with "RangeError: Maximum call stack size exceeded"

Adding `"strictNullChecks": true` to `tsconfig.json` fixes the issue for me (the test still fails but that's because I removed the non-relevant code).

**Comment by sjinks** [comment] 2021-12-20 16:34
Running `npm i objection@2 knex@"<0.95.0"` and updating the imports fixes the issue.

**Comment by sjinks** [comment] 2021-12-20 16:36
Replacing `QueryBuilder<ImageModel>` with `QueryBuilder<Model>` also fixes the issue :-)

**Comment by koskimas** [comment] 2021-12-20 18:17
I don't have time to debug or fix this for you. You'll have to do it yourself. I'll merge the PR.

**Comment by JeongJuhyeon** [comment] 2021-12-21 00:58
@hkjeffchan 

I copied your example, with "strict: true" I am not getting any error and inference works fine.

**Comment by JeongJuhyeon** [comment] 2021-12-21 01:02
I find the "strict: true" thing almost to be the opposite.
I've copied the example and at Typescript@4.5.2. "strict: true": No error, inference works but performance is very slow; it takes ~5 seconds for any kind of inference to pop up. "strict: false": No error, inference works and everything is very fast.

**Comment by hkjeffchan** [comment] 2021-12-21 05:56
> > Already set tsconfig to
> > "strict": true,
> 
> Are you sure? Your example won't compile in strict mode. `id: number;` and `name: string;` won't work in strict mode.

sorry, forgot to mention. The following is set:

"strictPropertyInitialization": false

**Comment by hkjeffchan** [comment] 2021-12-21 11:01
Another found:

Downgraded typescript to 4.3 works like a charm even with "strictNullChecks": true

**Comment by sjinks** [comment] 2021-12-21 11:56
`"typescript": "<4.5.3"` works.

**Comment by Linksku** [comment] 2021-12-30 07:09
Linking my fix without downgrading TS: https://github.com/Vincit/objection.js/issues/2132#issuecomment-1001968056

**Comment by koskimas** [comment] 2021-12-30 23:33
Thank you @Linksku! Awesome work!

**Comment by koskimas** [comment] 2021-12-30 23:57
@Linksku may have found the fix [here](https://github.com/Vincit/objection.js/issues/2132#issuecomment-1001968056). Their fix is implemented in 3.0.1. Please try it out and report if it fixes all your issues.

**Comment by hkjeffchan** [comment] 2022-01-03 05:27
> @Linksku may have found the fix [here](https://github.com/Vincit/objection.js/issues/2132#issuecomment-1001968056). Their fix is implemented in 3.0.1. Please try it out and report if it fixes your issues.

Would you push 3.0.1 to npm package? Thanks.

**Comment by hkjeffchan** [comment] 2022-01-03 05:36
3.0.1 + TS 4.5.4: Still RangeError: Maximum call stack
3.0.0 + TS 4.5.2: No error

**Comment by hanstf** [comment] 2022-01-03 05:46
do we still need to add the `"strict": true` for objection 3.0.1 ? when I set `"strict": false`, I am still getting the `RangeError `

**Comment by koskimas** [comment] 2022-01-03 17:03
Thanks @hkjeffchan. So the change didn't seem to be enough. I don't know why, but I'm unable to reproduce any of these typescript bugs. Could somebody please create a standalone reproduction for these?

**Comment by thejuan** [comment] 2022-01-05 03:16
Objection: 3.0.1
Typescript: 4.5.4

This generates the errors
```
import { Model, QueryBuilder } from "objection";

export class Base<T> extends Model {
    id?:T;
}

export class NumberModel extends Base<number>{}



interface IExample {
    scopeQuery<T extends NumberModel>(where: QueryBuilder<T>):void
}

export class Example implements IExample{

   public scopeQuery<T extends NumberModel>(where: QueryBuilder<T>){
       return null;
   }
}
```

Sometimes I can get it to spit this error out instead of crashing
`Excessive stack depth comparing types 'UpsertGraphMethod<?>' and 'UpsertGraphMethod<?>'.`

**Comment by thejuan** [comment] 2022-01-05 03:20
A note on strict, it crashes before strict gets enforced. i.e. remove the constructor so id is uninitialised, it still crashes

**Comment by koskimas** [comment] 2022-01-06 14:07
Doesn't generate the error when I run it.

**Comment by hkjeffchan** [comment] 2022-01-10 19:01
> Doesn't generate the error when I run it. By a reproduction I mean the whole project, tsconfig and everything.
@koskimas 

https://github.com/hkjeffchan/obj3rangeError

change typescript to "<4.5.3" runs perfectly

**Comment by jmeyers91** [comment] 2022-01-14 19:05
In our case, the bug seems to be caused by a cyclical type definition. Here's the reproduction repo:

https://github.com/jmeyers91/objection-3-tsc-stack-error

```
import { Model } from "objection";

class SoftDeleteQueryBuilder<
  M extends SoftDeleteModel,
  R = M[]
> extends Model.QueryBuilder<M, R> {
  SingleQueryBuilderType!: SoftDeleteQueryBuilder<M, M>;
}

export default class SoftDeleteModel extends Model {
  QueryBuilderType!: SoftDeleteQueryBuilder<this, this[]>;
}
```

```
/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:94444
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at indexSignaturesRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:54056:34)
    at structuredTypeRelatedToWorker (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53466:47)
    at structuredTypeRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53084:30)
    at recursiveTypeRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53055:53)
    at isRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:52648:34)
    at isPropertySymbolTypeRelated (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53641:24)
    at propertyRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53673:31)
    at propertiesRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53861:43)
    at structuredTypeRelatedToWorker (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53460:34)
    at structuredTypeRelatedTo (/Users/james/projects/objection-3-tsc-stack-error/node_modules/typescript/lib/tsc.js:53084:30)
    ```

**Comment by kvenn** [comment] 2022-01-26 20:42
## Initial problem

Objection.js: v3.0.1
TS: v4.5.4

We're also having this issue. I can't provide a repo with the error, but I can talk through what I was seeing which will hopefully help debugging. But it's very strange as the repo has no TypeScript errors and none of the other issues people in this thread have referenced.

In the following code sample, uncommenting the `doSomething` function caused the `Maximum call stack size exceeded` error in `ts-node`. Nothing is calling that function. The name of the function didn't impact anything (neither did changing the return type and method body). `yarn tsc --noEmit` also succeeds in both cases (commented or uncommented). So only `ts-node` is failing when uncommented.

Commenting it out again made ts-node run without a problem. We have a very vanilla use of Objection.js so far.

```typescript
export class AnswerModel extends BaseModel {
	static tableName = 'answers'

	// Default
	id?: string
	text?: string
	imageUrl?: string

	// doSomething() {
	// 	console.log('Test')
	// }
}
```

## Attempted solution 1
Objection.js: v3.0.1
TS: v4.5.2

We downgraded the TS version as some had recommended. And it fixed the error in `ts-node`. We kept developing for another week and the error popped up again (again, unrelated to any type errors).

## Attempted solution 2
Objection.js: v2.2.18 (latest 2.x version)
TS: v4.5.2

We downgraded Objection (and kept the downgraded TS) and the error seems to have gone away again. But we'd love to be on 3.0.x. I will update this comment if we see it again.

**Comment by david-wb** [comment] 2022-02-12 01:05
I can confirm this happens on latest versions of Objection and TypeScript when `strictNullChecks` is set to `true`. I definitely want to use `strictNullChecks` though so I help this will be fixed soon.

**Comment by SteveDeWald** [comment] 2022-02-16 20:14
Here's another reproduction.  Tested with objection `3.0.1` and typescript `4.5.x`

Run:
```bash
tsc --strictNullChecks index.ts
```

```typescript
// index.ts

import { Model } from 'objection';

class ModelA extends Model {
  id!: number;
}

class ModelB extends Model {
  id!: number;
  static relationMappings = {
    model: {
      relation: Model.HasManyRelation,
      modelClass: ModelA,
      join: { to: "", from: "" },
    },
  };
}
```

Outputs:
```sh
RangeError: Maximum call stack size exceeded
```

I should note that splitting `ModelA` and `ModelB` into separate files with `modelClass: require('./ModelA')` like in the examples fixes the error.  It's not a circular reference though, so I don't think that should be necessary in this case.

**Comment by SteveDeWald** [comment] 2022-02-16 22:33
Another way to reproduce it is to upgrade the `examples/koa-ts` repo to TypeScript `4.5.3` (oddly `4.5.2` works in this case) and add one of the following to `tsconfig.json`:

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

or

```json
{
  "compilerOptions": {
    "strictFunctionTypes": false
  }
}
```

Compiling the project will reproduce the error:
```sh
> npx tsc

RangeError: Maximum call stack size exceeded
```

**Closed** 2022-06-14 07:30 UTC
