### ISSUE TITLE
$relatedQuery().insert() race condition

### ISSUE THREAD

**Issue by peteyy** [Vincit/objection.js#352] opened 2017-04-05 13:07 UTC
```
return SomeTable
                .query()
                .select(...)
                .limit(1)
                .first()
                .then((someTable) => {
                    return someTable
                        .$relatedQuery('values')
                        .delete()
                        .then(() => Promise.map(someTableValues, (someTableValue) =>
                            someTable
                                .$relatedQuery('values')
                                .insert(someTableValue))
                });
```

The query runs in mysql which doesn't support batch insert so I'll have to manually map over the object and add it as a `$relatedQuery`. It works fine if I try to insert a single element, because it will assign that newly created element to the values array. But if there are multiple elements added, each of them will overwrite the current values array, therefore I'm going to end up with a single element in my array.

I will end up with a single element array in the `someTable` instance. Is there a way to work around this problem without refetching the data?

**Comment by koskimas** [comment] 2017-04-05 15:38
Maybe this:

```js
SomeTable
  .query()
  .limit(1)
  .first()
  .then(someTable => {
    return someTable.$relatedQuery('values').delete().then(() => {
      return someTable.$relatedQuery('values').insertGraph(someTableValues);
    });
  });
```
? Don't know if it works. If it doesn't, you can always just manually assign the return value of the `Promise.map` operation to `someTable.values`.

This would get fixed with #323.

**Comment by peteyy** [comment] 2017-04-05 18:22
manually assigning is not good enough because `.toJSON` breaks in that case. I'd have to manually convert each of them to json.

**Comment by koskimas** [comment] 2017-04-05 18:26
You are doing something wrong. There is absolutely no magic in what `relatedQuery.insert` does with the models. All it does is assign them to the property named after the relation. If you have a relation named `foo` and you assign a model (or a list of models) to a property `foo` `toJSON` will get called for them also. If you really have a problem with this, please post a code snippet that reproduces the bug.

**Comment by koskimas** [comment] 2017-04-14 09:19
Closing due to lack of activity. Please reopen if the problem remains.

**Closed by koskimas** 2017-04-14 09:19 UTC
