### ISSUE TITLE
Virtual field with promise

### ISSUE THREAD

**Issue by Allam76** [Vincit/objection.js#264] opened 2016-12-21 09:36 UTC
In continuation with #261. 

Would it be possible to add a new query inside the getter method? Right now, it seems the getter method does not wait for the promise to return before sending the result out.

On a broader note, I would like to add a materialized path of parent relationships as a virtual field in a model and it seems I could have two options:
1) as above, add a new query inside the getter or hook.
2) change the original query to include the eager loading if the query asks for the path.

This is complicated by the fact that I'm using the graphql addition, so my possibilities to change the query itself are limited.

Many thanks!

**Comment by koskimas** [comment] 2016-12-21 13:29
duplicate of #175

**Closed by koskimas** 2016-12-21 13:29 UTC

**Comment by Allam76** [comment] 2016-12-21 13:31
OK, by extending the query builder of the model and add a custom select method:
`class MyQueryBuilder extends QueryBuilder {
  select(fields){
    super.select(fields).eager('parent.^');
  }`
This basically always add an eager parent loading. This extended builder is then added to the model:
`  static get QueryBuilder() {
    return MyQueryBuilder;
  }`
Then getter:
`  get path(){
    var path = "";
    this.$traverse(function(model,parent,relationName){
      path = "/" + model.id + path;
    });
    return path;
  }` and json formatter:
`  $formatJson(obj) {
    obj = super.$formatJson(obj);
    obj.path = this.path;
    return obj;
  }`
Then the following query works:
`ES6.query().select('*').where({id:"aaa"}).then(function(data){})`
However the select method is not used in the graphql module. Any better ideas?

**Comment by Allam76** [comment] 2016-12-21 14:06
OK, I checked the afterGet method that retuns a promise. It will not work with the grapql implementation. I'll open a seperate issue there.
