### ISSUE TITLE
Recommendation: rename the project

### ISSUE THREAD

**Issue by janl** [Vincit/objection.js#10] opened 2015-07-03 15:03 UTC
The name is very insulting. I highly recommend changing it ASAP.

**Comment by laicosly** [comment] 2015-07-03 15:59
+1

**Comment by uncedric** [comment] 2015-07-03 16:04
+1, if you are going to be offensive asshole.js was a better option

**Comment by vinimdocarmo** [comment] 2015-07-03 16:33
+1

**Comment by elhigu** [comment] 2015-07-03 20:50
Actually initial idea for the name came from me. It is interesting what different people 
considers offensive. To me offensiveness of a word comes from how one uses it. 

When it is directed to person, it is an insult and generally no one ever uses it with its “medical” meaning. 

I would never use that word to describe person and that kind of made think that the name  is suitable to describe ORM which does not try to be too smart.

Anyhow its clear that some people does not think that way and are insulted by it. I really don’t want to insult anyone so I'm good for name :)

+0.5

ps. I'm sorry to everyone offended by it :) 

psps. this got me to think of which are really those lines which should not be crossed when naming public libraries. looks like "words used to insult people" is one of them :)

**Comment by novacrazy** [comment] 2015-07-04 00:08
![11693064_10203182760168945_1850654781_n](https://cloud.githubusercontent.com/assets/4708645/8505703/677d1cb4-21b5-11e5-8efe-ea257e3a16c7.jpg)
I like the name. It's refreshing. 

If people are going to get offended at code anyway, though, then maybe you should try to name parts of the library more generically. Most of your examples are fairly unbiased and don't mention 'Moron' at all, so it's not like people are going to be staring at the word 'Moron' constantly. So just renaming MoronModel to Model so people can import it like:

```javascript
import {Model, QueryBuilder} from 'moron';
```

and then never see the word moron for the rest of their code would be nice. 

If you are going to rename the project anyway, removing the 'r' and making it Moon.js sound kind of neat to me.

**Comment by laicosly** [comment] 2015-07-04 01:46
not offended, just think moron.js isn't an awesome name.  moon.js is rad.

**Comment by uncedric** [comment] 2015-07-04 04:16
moon.js sounds great.... but it's already taken by an abandoned project

**Comment by novacrazy** [comment] 2015-07-04 04:20
Yeah, I noticed that after I said it. It may have an NPM package, but it doesn't even have a repo or readme, so I think it's safe to use that name. `none license` is pretty permissive. 

Just name the new package `moon-js`, `moon-orm` or something derivative like that. `moon-js` is open right now.

**Comment by firebombzero** [comment] 2015-07-04 06:00
Please don't change the name.

**Comment by koskimas** [comment] 2015-07-04 07:57
I didn't realise people can get offended by that word. Insulting people really wasn't the goal here. In my mind, the word means nothing if not directed to a person. I never considered the meaning "mentally challenged", which I can understand being offensive to someone.

I want the focus to be in the code, not the name. So if the name is causing this much bad attention (I don't mean just this issue), then we should consider changing the name or at least the parts of the code that mention the name as @novacrazy suggested. 

The name already has some, well, name so I don't want to change it lightly. I'll leave the ticket open for now for more opinions. Please write your thoughts here. +1/-1, suggest a name, anything.

**Comment by Craicerjack** [comment] 2015-07-04 13:29
I think you should keep the name. With the plethora of libraries out there its hard to get notice. The name is probably the only reason I checked this out. That been said, really nice library. I dont see why its insulting. Its not as if youre calling anyone a moron. I dont like moon.js at all.

**Comment by novacrazy** [comment] 2015-07-05 09:09
I posted that Baymax image above because I don't think the name is a serious issue and if anyone is offended by it then they should grow thicker skin. Also I was just being cute with the "remove the r and make it another library" thing. 

However, I do still think you should rename the library components. It makes it simpler and does help maintain a bit more professionalism within the code.

**Comment by koskimas** [comment] 2015-07-05 09:24
Yeah, I agree with the component renaming idea. The reason the components are prefixed with `Moron` is to help IDEs like IntelliJ IDEA with autocompletion. If `MoronModel` is just `Model` and I annotate `@param {Model} someModel` somewhere in the code, ctrl-clicking the `Model` will probably show 73 different classes named `Model` found under the node_modules. Maybe I could prefix the classes with something else, but everything else seems like objective-c :D

**Comment by novacrazy** [comment] 2015-07-05 09:48
Ah, I hadn't actually considered how autocomplete/introspection stuff would handle that. Most of the time my projects are complicated enough I give up on autocomplete having any serious use. 

You could just export components both with and without the `Moron` prefix and let people choose whatever works best on their IDE?

**Comment by koskimas** [comment] 2015-07-05 10:14
I would still have to leave the class names and annotations with the moron prefix. They would still show up in the API docs and when you browse the code. I'll probably give up on the autocomplete too, as most javascript developers/libraries have and just remove the prefixes.

**Comment by Hunter-Github** [comment] 2015-07-05 15:28
Sure you can leave the name if you want the notoriety. There are precedents: [GIMP](https://en.wikipedia.org/wiki/GIMP) and [Pidora](http://zenit.senecac.on.ca/wiki/index.php/Pidora_Russian), trailblazers for moron.js.

**Comment by killswitch** [comment] 2015-07-05 19:44
Keep it. I'm also going to start using moron.js just for the name.

**Comment by aleksih** [comment] 2015-07-06 10:13
I think the name is great. Moron is an wordly implication on how a person behaves and it isn't insulting lest it is used in an insulting capacity. The name also fits very well on ORM.

If you get insulted by words people use to describe ideas and a ton of work they have done to deliver those ideas to people then maybe you should take a look into the mirror. Moron doesn't have a religious context, it doesn't insult a belief or an idea and it is very general in general, so the problem is with the one hearing the word, not the (objective) meaning the word has.

**Comment by koskimas** [comment] 2015-07-12 21:36
We have decided to change the name. Now bring on suggestions for a new name! I'm not a fan of moon.js.

**Comment by Craicerjack** [comment] 2015-07-12 22:43
Objection.js? 

Works on a few levels. And moon is, imo, not a good name.

-----Original Message-----

**Comment by koskimas** [comment] 2015-07-12 22:48
I love it! Taken in npm though, and a pretty well known [objective-c library](https://github.com/atomicobject/objection)

**Comment by kkemple** [comment] 2015-07-12 23:50
I like `norm.js` Node - ORM, nice play on words...

`norm` is taken on NPM but it is not maintained it seems :: https://www.npmjs.com/package/norm
github repo for NPM lib 404s so you may be able to get name, or could do `normjs` for package and norm in code... fwiw

**Comment by uncedric** [comment] 2015-07-15 03:33
IMHO "norm" sounds good, maybe we should try to contact the owner of that package... or have you come up with another one?

**Comment by koskimas** [comment] 2015-07-20 15:05
`norm.js` is a bit too normal for me..

**Comment by firebombzero** [comment] 2015-07-20 19:51
The original name is fine. This ticket should have been closed as soon as it was open. Why are people still wasting time with this?

On July 20, 2015 8:05:52 AM PDT, "Sami Koskimäki" <notifications@github.com> wrote:
>`norm.js` is a bit too normal for me..
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Vincit/moron.js/issues/10#issuecomment-122912835

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Craicerjack** [comment] 2015-07-20 21:32
Completely agree with firebombzero

-----Original Message-----

**Comment by elhigu** [comment] 2015-07-20 21:54
@firebombzero and @Craicerjack that would have been done if it wouldn't cast any negative effect on the project. Changing name seems to cause less problems. Otherwise slight discrimination by persons who takes it seriously will continue. So choosing to change name seems to be smaller bad of two. 

Also ticket was not closed, because it was good to have place for these discussions :) Rather here than in various separate forums in interwebs.

**Comment by uncedric** [comment] 2015-08-06 03:34
In my humble opinion I think it would help to gain users if we choose a catchy but at the same time a "professional"  name. I know "moron" sounds fun, but personally I would prefer this project to grow and be adopted by many users who help to improve it rather than rejecting them **indirectly** by having an "unprofessional" name.

Said that, I do not choose a library based on how good it sounds to me (professional, serious, catchy). But I think there are great programers that do care about that and we should try to integrate them.

Finally, I don't bother the name "moron", but I think there are good reasons to change it and I am ok with that, that's why I think this issue is valid and  should be dicussed :).

**Comment by firebombzero** [comment] 2015-08-06 04:14
Why is this issue still being discussed? This is the least important aspect of the project and yet, of course, it's what everyone is wasting their energy on. It is irrelevant. It's a footnote, marginalia. This should have been closed the second it was opened. It does not matter at all and should never have gotten into anyone's head.

**Comment by koskimas** [comment] 2015-08-07 13:20
Moron.js will be renamed to objection.js along with the 0.2.0 release in the near future. @janl Can I have my programming licence back now? :D

**Comment by koskimas** [comment] 2015-08-07 13:21
@Craicerjack Thanks for the awesome name suggestion!

**Comment by Craicerjack** [comment] 2015-08-07 17:01
My pleasure. I'm honoured. 

-----Original Message-----

**Comment by jzumbrun** [comment] 2015-08-22 16:36
I like moron.js. It is very marketable and easy to remember.

**Closed** 2015-08-25 06:25 UTC

**Comment by janl** [comment] 2015-11-24 19:22
@koskimas better late then never, but totally! :dancer: 

Also Objection.js is a a really good name 👍
