### ISSUE TITLE
Bug: 0.9 upsertGraph HasMany no insert in one particular case

### ISSUE THREAD

**Issue by Allam76** [Vincit/objection.js#595] opened 2017-11-04 11:17 UTC
It seems to be a bug in 0.9 with upsertGraph in the following case:

Model:
 grandparent (update) (BelongsToOne parent)-> parent (update) (HasMany child)-> child(insert). 

In this case in the dependency graph, the parent get markAsHandled set after established that it has a dependency to grandparent. After this, however, is determined that child also has dependency to parent but markAsHandled for parent is already set.

This leads to hasUnresolvedDependencies failing for child with numHandledNeeds = 0 and needs = 1. This leads to no insert.

markAsHandled should probably be called after all dependencies have been resolved.
As a workaround I set manually in DependencyGraph:

```js
    if (rel) {
      if (rel instanceof HasManyRelation) {
        node.needs.push(new HasManyDependency(parentNode, rel));
        parentNode.isNeededBy.push(new HasManyDependency(node, rel));
// new line
        node.numHandledNeeds++;
``` 
This will of course only work in my particular case.

Could maybe be useful with an error/warning message for unresolved dependencies?
Many thanks.

**Comment by koskimas** [comment] 2017-11-04 11:28
It's a bit difficult to nunderstand your explanation. Could you write a reproduction or a test case?

**Comment by koskimas** [comment] 2017-11-05 09:59
Or at least post the failing query here. I'm not being difficult, I just don't understand the problem.

**Comment by Allam76** [comment] 2017-11-06 09:26
Hello there. I managed to create a specific case [here](https://github.com/Allam76/objection.js/tree/bug-upsertgraph/tests/upsertGraph) or copy paste:

sql:
```
drop table if exists grand_parent, parent, child, child_1;
create table grand_parent(
	id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text,
    constraint grand_parent_pkey primary key(id)
);
create table parent(
	id uuid NOT NULL DEFAULT uuid_generate_v4(),
    parent_id uuid,
    name text,
    constraint parent_pkey primary key(id)
);
create table child(
	id uuid NOT NULL DEFAULT uuid_generate_v4(),
    parent_id uuid,
    name text,
    constraint child_pkey PRIMARY KEY(id)
);
create table child_1(
	id uuid NOT NULL DEFAULT uuid_generate_v4(),
    parent_id uuid,
    name text,
    constraint child_1_pkey PRIMARY KEY(id)
);
insert into grand_parent values('22e1c365-a066-4398-8155-5a87e1614759', 'root');
insert into parent values('22e1c365-a066-4398-8155-5a87e1614760', '22e1c365-a066-4398-8155-5a87e1614759', 'root');
```
test.js:
```
const objection = require('../../lib/objection');
const Model = objection.Model;
const Knex = require('knex');

const knex = Knex({
  client: 'pg',
  connection: {
    database: 'test',
    password: 'password',
    user: 'martin'
  }
});

Model.knex(knex);

class GrandParent extends Model {
    static get tableName() {
        return 'grand_parent';
    }    
    static get relationMappings() {
        return {
            Parents:{
            relation: Model.HasManyRelation,
            modelClass: Parent,
                join: {
                    from: 'grand_parent.id',
                    to: 'parent.parent_id'
                }
            }
        }
    }  
}

class Parent extends Model {
    static get tableName() {
        return 'parent';
    }    
    static get relationMappings() {
        return {
            Child:{
            relation: Model.HasManyRelation,
            modelClass: Child,
                join: {
                    from: 'parent.id',
                    to: 'child.parent_id'
                }
            }
        }
    }  
}


class Child extends Model {
    static get tableName() {
        return 'child';
    }
    static get relationMappings() {
        return {
            Parent:{
            relation: Model.BelongsToOneRelation,
            modelClass: Parent,
                join: {
                    from: 'child.parent_id',
                    to: 'parent.id'
                }
            }
        }
    }  
}
class Child1 extends Model {
    static get tableName() {
        return 'child_1';
    }
    static get relationMappings() {
        return {
            Parent:{
            relation: Model.BelongsToOneRelation,
            modelClass: Parent,
                join: {
                    from: 'child_1.parent_id',
                    to: 'parent.id'
                }
            }
        }
    }  
}

var input = {
    id: "22e1c365-a066-4398-8155-5a87e1614759",
    Parents:[{
        id: "22e1c365-a066-4398-8155-5a87e1614760",
        name: "parent",
        Child1:[{name:"TestChild1"}],
        Child:[{name:"TestChild"}]
    }]
}
GrandParent.query().upsertGraph(input, {relate:true, insertMissing:true}).debug().then(data=>console.log(data)).catch((error)=>{
    console.log(error);
});
```

The problem only occurs if 2 child models should be inserted at the same time, then the first one gets inserted, then the makeAsHandled on the parent get set, which gives the inconsistency.

**Comment by koskimas** [comment] 2017-11-06 09:57
@Allam76 You have not defined the relation `Child1` for `Parent`. Therefore it doesn't get inserted.

**Comment by Allam76** [comment] 2017-11-06 10:06
oh sorry, very stupid of me.....
It seems I need to give you my full scenario. I don't seem to be able to reproduce this in any simpler way....

**Comment by Allam76** [comment] 2017-11-06 10:47
updated the test [here](https://github.com/Allam76/objection.js/tree/bug-upsertgraph/tests/upsertGraph). Now get the proper error.

use test.sql to create database, reset.sql between runs.

**Comment by koskimas** [comment] 2017-11-06 10:57
I'm sorry, but that's way too complex reproduction. I just spent 20 minutes on it and got absolutely nowhere.

The reason why I want easy reproductions in these cases is my limited time. 90% of these issues end up being user errors and have nothing to do with objection. If I spend hours on each of them these issues would take up all my time.

I'm not saying this is necessarily your error or that there are no bugs in objection, but I simply cannot debug hundreds of lines of your code for you. The reproduction needs to be a simple single file with clear instructions on how to run it.

If you cannot create a simple reproduction then the problem is probably in your code and as much as I would love to help you, I just don't have the time.

**Comment by koskimas** [comment] 2017-11-06 11:02
The example doesn't even run. You `require` stuff that doesn't exist.

**Comment by Allam76** [comment] 2017-11-06 11:06
I totally understand, I'll try to reduce the problem as much as possible.

**Comment by Allam76** [comment] 2017-11-06 12:04
Ok, [this](https://github.com/Allam76/objection.js/blob/bug-upsertgraph/tests/upsertGraph/test-no-other-file.js) is a single file that can be run anywhere in a project where objection, knex and postgresql is present.

I cleaned away any non relevant stuff.

Please note it creates a posgresql database named bug. Requires standard postgres user.

**Comment by koskimas** [comment] 2017-11-06 13:39
Thank you! Now there's a reproduction I can work with 👍 

This is not actually a bug, but may be a missing feature. It depends on what you are trying to achieve with this. Are you trying to say: `Relate if id is found in the database, otherwise insert a new row.`?

If that's what you want, unfortunately it's not supported at the moment. What `insertMissing` means is `If parent doesn't have a child by the given id, insert a new item.`. It doesn't check if the id already exists in the database. Implementing this would be all kinds of difficult too, since we would need to do a bunch of new queries to find out if the given item exist in the database. Not to mention what to do to relations that are found, but their children are not... My brain explodes just thinking about implementing this.

If you are trying to simply insert the ones with ids, you can just remove the `relate` option:

```js
// This one can be run in standalone

const objection = require("objection");
const Base = objection.Model;
const Knex = require("knex");

async function test() {
  try {
    var knex = require("knex")({
      client: "pg",
      connection: { host: "localhost", database: "postgres" }
    });

    // Will create a db called bug
    await knex.raw("DROP DATABASE IF EXISTS bug;");
    await knex.raw("CREATE DATABASE bug;");

    knex = require("knex")({ client: "pg", connection: { database: "bug" } });
    await knex.raw(sql);
    Base.knex(knex);

    const bsa = await BusinessDocument.query()
      .eager("UsagePoint")
      .where({ usagepoint_id: null });

    const data = {
      id: bsa[0].id,

      UsagePoint: {
        id: "0360933f-7746-4d4c-aabf-9a248e8629f4",

        Meter: [
          {
            meter_identification: "000000000010000002"
          }
        ],

        Address: {
          streetname: "Hello",
          house_number: "AA",
          postcode: "1000"
        }
      }
    };

    const output = await BusinessDocument.query().upsertGraph(data, {
      insertMissing: true
    }).debug();

    const inserted = await BusinessDocument
      .query()
      .eager('UsagePoint.[Meter, Address]');

    console.dir(inserted, {depth: null});
  } catch (error) {
    console.log(error);
  }
}

test();

class Address extends Base {
  static get tableName() {
    return "address";
  }
  static get relationMappings() {
    return {};
  }
}

class BusinessDocument extends Base {
  static get tableName() {
    return "business_document";
  }

  static get relationMappings() {
    return {
      UsagePoint: {
        relation: Base.BelongsToOneRelation,
        modelClass: UsagePoint,
        join: {
          from: "business_document.usagepoint_id",
          to: "usagepoint.id"
        }
      }
    };
  }
}

class Meter extends Base {
  static get tableName() {
    return "meter";
  }

  static get relationMappings() {
    return {
      UsagePoint: {
        relation: Base.BelongsToOneRelation,
        modelClass: UsagePoint,
        join: {
          from: "meter.usagepoint_id",
          to: "usagepoint.id"
        }
      }
    };
  }
}

class UsagePoint extends Base {
  static get tableName() {
    return "usagepoint";
  }

  static get relationMappings() {
    return {
      Address: {
        relation: Base.BelongsToOneRelation,
        modelClass: Address,
        join: {
          from: "usagepoint.address",
          to: "address.id"
        }
      },

      BusinessDocument: {
        relation: Base.HasManyRelation,
        modelClass: BusinessDocument,
        join: {
          from: "usagepoint.id",
          to: "business_document.usagepoint_id"
        }
      },

      Meter: {
        relation: Base.HasManyRelation,
        modelClass: Meter,
        join: {
          from: "usagepoint.id",
          to: "meter.usagepoint_id"
        }
      }
    };
  }
}
var sql = `
create extension if not exists "uuid-ossp";
CREATE TABLE public.business_document
(
    id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
    usagepoint_id uuid,
    CONSTRAINT business_document_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
ALTER TABLE public.business_document
    OWNER to samiko;
CREATE TABLE public.usagepoint
(
    id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
    ean character varying(30) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    address uuid,
    CONSTRAINT usagepoint_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
ALTER TABLE public.usagepoint
    OWNER to samiko;
CREATE TABLE public.address
(
    id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
    streetname text,
    house_number text,
    postcode text,
    CONSTRAINT address_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
ALTER TABLE public.address
    OWNER to samiko;
CREATE TABLE public.meter
(
    id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
    meter_identification text COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    usagepoint_id uuid,
    CONSTRAINT meter_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
ALTER TABLE public.meter
    OWNER to samiko;
INSERT INTO business_document (id) VALUES ('22e1c365-a066-4398-8155-5a87e1614760');
INSERT INTO usagepoint (id) VALUES ('22e1c365-a066-4398-8155-5a87e1614761');
`;

```

**Comment by Allam76** [comment] 2017-11-06 13:52
Glad to hear that the example works better:-)

That is exactly what I'm trying to do.

You can disregard the ```insertMissing``` it has no impact on the case, I put it there by mistake. 
I don't really want to insert with an id, when I want to insert, I simply don't put any id at all and objection and the db figures out the rest. This works great, except in the case where I want to insert two children at the same time, on an existing parent. In all other of my very complex cases, it works like a charm:-)

Funnily, if you put an extra line at 83 in DependencyGraph.js:  ```node.numHandledNeeds++;``` then the problem is solved and all works perfectly.

The problem is that Usagepoint markAsHandled is called before the execution of Meter, therefore an inconsistency in hasUnresolvedDependencies is detected for Meter and the node is not inserted.

**Comment by koskimas** [comment] 2017-11-06 13:59
If `insertMissing` is there by accident, then your example is broken. You can only relate rows that exist in the database. In your example `0360933f-7746-4d4c-aabf-9a248e8629f4` doesn't exist inte database, and therefore cannot be related. Also you cannot give relations for a row you are relating. That row already exists in the database, and cannot be upserted.

**Comment by koskimas** [comment] 2017-11-06 14:00
Your, `node.numHandledNeeds++` isn't a fix. Try to run the objection tests with that change 😄

**Comment by Allam76** [comment] 2017-11-06 14:03
With ``` {relate:true}``` it is all good :smile:

**Comment by Allam76** [comment] 2017-11-06 14:06
Admittedly, I did not run the objection tests with an extra``` node.numHandledNeeds++ ``` :anguished: Im sure this is an ugly fix..

However, all my complex upsertGraph stuff runs like a charm with it, so it can't be that bad :wink:

**Comment by Allam76** [comment] 2017-11-06 14:08
The trick is to call ``` markAsHandled() ``` for each parent node when all children already have been processed... But how do one know that?

**Comment by koskimas** [comment] 2017-11-06 14:25
`markAsHandled` means `this model has been inserted` and should only be called once.

**Comment by koskimas** [comment] 2017-11-06 14:25
Can I close this issue?

**Comment by Allam76** [comment] 2017-11-06 14:27
The problem is that it is called too early. Could we make it be called only after all children have been processed?

**Comment by koskimas** [comment] 2017-11-06 14:28
No. Why would I do that? The algorithm works as it is designed.

**Closed by koskimas** 2017-11-06 14:28 UTC
