### ISSUE TITLE
Global query and eager conditions

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#409] opened 2017-06-13 19:17 UTC
Hello again,
Trying to add a filter/condition/where to every single query.
I have a BaseModelQueryBuilder extending from QueryBuilder and I have a bunch of stuff in there including...
```
constructor(...args) {
        super(...args);
        this.onBuild(builder => {
            if (!builder.context().withArchived) {
                builder.modify(function (queryBuilder) {
                    if (builder._modelClass.jsonSchema.properties.is_deleted) { 
                        queryBuilder.where("is_deleted", false); // Weed out deleted!!
                    }
                })
            }
        });
    }
```
But the `is_deleted` column is "ambiguous" because of the joins.
Beyond writing a javascript filter in each `$afterGet` or `$parseDatabaseJson` and/or putting a filter in every relationship or query, can you think of a better to do this? I'm trying to avoid putting `(notDeleted)` filters in every eager after every model.

Here's the error I'm getting witih some of my queries for this:
``` 
sql: 'select "user".*, "user_group"."group_id" as "objectiontmpjoin0" from "user" inner join "user_group" on "user_group"."user_id" = "user"."user_id" where "is_deleted" = ? and "user_group"."group_id" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' }
[[12:18:56.746]] [LOG]   { error: column reference "is_deleted" is  #ambiguous...
```

**Comment by allxie** [comment] 2017-06-13 19:26
Potentially fixed with...
```queryBuilder.where(`${builder._modelClass.tableName}.is_deleted`, false);```

**Comment by koskimas** [comment] 2017-06-13 19:41
It's better to use the public `builder.modelClass()` method instead of the private `_modelClass` property. There is no guarantee that I (or someone else) won't rename or move the `_modelClass` property.

**Comment by allxie** [comment] 2017-06-13 19:50
Oh, awesome. Thanks for the tip!

**Comment by fl0w** [comment] 2017-06-19 23:47
Note that the is_deleted case will not build when using `*joinRelated`(and friends).

**Comment by koskimas** [comment] 2017-06-20 10:13
@allxie Did you reopen this on purpose?

**Comment by allxie** [comment] 2017-06-20 14:31
Unfortunately reopening this issue. The above code does filter out all columns where is_deleted is true on the initial model queried, but I'd love to filter out all eagered models, too, including join tables. 
For example, I have a page_relationship model who's is_deleted gets ignored despite this query.
I tried adding ... `filter: (builder)=>{builder.where('page:page_relationship.is_deleted', false)},` or `filter: (builder)=>{builder.where('page_relationship.is_deleted', false)},` to the models, but those won't recognize page_relationship. I get a `Missing FROM-clause entry for a table` error. I'd love to be able to put a cascading filter in my baseModel.
Any tips?

**Comment by koskimas** [comment] 2017-06-20 14:50
If you have installed the query builder for all models, your code from the original post should work. You only showed a small part of your setup, but I'm assuming you have something like this going on:

```js
class CustomQueryBuilder extends QueryBuilder {
  constructor(...args) {
    super(...args);

    this.onBuild(builder => {
      const withArchived = builder.context().withArchived;
      const modelClass = builder.modelClass();
      const jsonSchema = modelClass.jsonSchema;

      if (!withArchived && jsonSchema.properties.is_deleted) {
        // You don't need the `modify` function here by the way.
        builder.where(`${modelClass.tableName}.is_deleted`, false);
      }
    });
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}

class Person extends BaseModel {
  ...
}

class Pet extends BaseModel {
  ...
}

// All other models also inherit from `BaseModel`.
```

If you are still using objection below 0.8 you need to have

```js
class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder;
  }

  static get QueryRelatedBuilder() {
    return CustomQueryBuilder;
  }
}
```

**Comment by allxie** [comment] 2017-06-20 18:38
~~ Alright, so I think I have mine set up that way. 
The query I'm testing out is the following...
```
async getPagesByDomain (domain_id) {
       
        let domain = await Page
            .query()
            .findById(domain_id)
            .eager('children(typePage)', eager.typePage); // eager.typePage is a filter. Going to move this over to the new namedFilters soon.
        return domain.children;

    }
```
This currently returns two pages. I'd like it to return only one of the two-- I'd like it to only return entries where the join table entry has is_deleted:false.  

Here are the relevant parts of the models: 
Page-->
```
static relationMappings = {
...
parents: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            //filter: (builder)=>{builder.where('PageRelationship.is_deleted', false)}, // <-- didn't work
            join: {
                from: 'page.page_id',
                through: {

                    from: 'page_relationship.child_id',
                    to: 'page_relationship.parent_id'
                },
                to: 'page.page_id'
            }
        },
        children: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            //filter: (builder)=>{builder.where('page:page_relationship.is_deleted', false)},  // <-- really didn't work
            join: {
                from: 'page.page_id',
                through: {
                    modelClass: PageRelationship,
                    from: 'page_relationship.parent_id',
                    to: 'page_relationship.child_id'
                },
                to: 'page.page_id'
            }
        }...
}
```
PageRelationship:
```
static relationMappings = {
        children: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Page`,
            //filter: {'page_relationship.is_deleted': false},  // <-- didn't work
            join: {
                from: 'page_relationship.child_id',
                to: 'page.page_id'
            }
        },
        parents: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Page`,
            //filter: {'page_relationship.is_deleted': false},  // <-- didn't work
            join: {
                from: 'page_relationship.parent_id',
                to: 'page.page_id'
            }
        }
    };
```
BaseModel (adjusted to look more like yours):
```
export default class BaseModel extends Model {

    static get QueryBuilder() {
        return BaseModeQueryBuilder;
    }

    static get QueryRelatedBuilder() {  
        // are you sure this is supposed to be QueryRelatedBuilder instead of RelatedQueryBuilder? I tried both. Nothing broke. Nothing worked, though.
        return BaseModeQueryBuilder;
    }
}

class BaseModeQueryBuilder extends QueryBuilder {

    constructor(...args) {
        super(...args);

        this.onBuild(builder => {
            const withArchived = builder.context().withArchived;
            const modelClass = builder.modelClass();
            const jsonSchema = modelClass.jsonSchema;

            if (!withArchived && jsonSchema.properties.is_deleted) {
                builder.debug().where(`${modelClass.tableName}.is_deleted`, false);
            }
        });
    }

    withArchived(withArchived) {
        this.context().withArchived = withArchived;
        return this;
    }

    softDelete(id, req) {
        let obj = {is_deleted: true};
        if(req) obj.modifier_id = req.user.user_id;
        return this.patchAndFetchById(id, obj);
    }
}

//BaseModel.QueryBuilder = BaseModeQueryBuilder;//<-- what I had before I added get  QueryBuilder()
//BaseModel.QueryRelatedBuilder = BaseModeQueryBuilder; // are you sure this is supposed to be QueryRelatedBuilder instead of RelatedQueryBuilder?
//BaseModel.RelatedQueryBuilder = BaseModeQueryBuilder; //<-- what I had before I added get   QueryRelatedBuilder()

```

The query that's getting run according to the debugger is this...
```
 'select "page".*, "page_relationship"."parent_id" as "objectiontmpjoin0" from "page" inner join "page_relationship" on "page_relationship"."child_id" = "page"."page_id" where "page_relationship"."parent_id" in (?) and object_data->>\'page_type\' = ?'
```
I want to get 'where "page_relationship"."is_deleted" = false' in there somewhere.

**Comment by koskimas** [comment] 2017-06-21 08:03
The problem is that the

```sql
 'select "page".*, "page_relationship"."parent_id" as "objectiontmpjoin0" from "page" inner join "page_relationship" on "page_relationship"."child_id" = "page"."page_id" where "page_relationship"."parent_id" in (?) and object_data->>\'page_type\' = ?'
```

query is actually for the `page` table. The `page_relationship` table is only joined to the same query. Your code in the `QueryBuilder` constructor only gets executed for `Page`. You should be able to do this as a workaround:

```js
        children: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            // You can see from the query you posted that the `page_relationship` table
            // is joined simply as `page_relationship`. You can use the same `context`
            // here to check if the deleted items should be omitted.
            filter: (builder) => builder.where('page_relationship.is_deleted', false),
            join: {
                from: 'page.page_id',
                through: {
                    modelClass: PageRelationship,
                    from: 'page_relationship.parent_id',
                    to: 'page_relationship.child_id'
                },
                to: 'page.page_id'
            }
        }
```

**Comment by allxie** [comment] 2017-06-21 15:46
Thanks Sami, but when I set it up that way...

```
children: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            filter: (builder) => builder.where('page_relationship.is_deleted', false),
            join: {
                from: 'page.page_id',
                through: {
                    modelClass: `${__dirname}/PageRelationship`,
                    from: 'page_relationship.parent_id',
                    to: 'page_relationship.child_id'
                },
                to: 'page.page_id'
            }
        },
```
I get the following error: 
`unhandled rejection: error: invalid reference to FROM-clause entry for table "page_relationship"`
I can't get the sql debugger to run when that errors, so that's all I have to work with.

**Comment by koskimas** [comment] 2017-06-21 15:54
Works for me:

```js
const { Model } = require('objection');
const Knex = require('knex');

const knex = Knex({
  client: 'sqlite3',
  useNullAsDefault: true,
  connection: {
    filename: 'test.db'
  }
});

Model.knex(knex);

class BaseModelQueryBuilder extends Model.QueryBuilder {
  constructor(...args) {
    super(...args);

    this.onBuild(builder => {
      const withArchived = builder.context().withArchived;
      const modelClass = builder.modelClass();
      const jsonSchema = modelClass.jsonSchema;

      if (!withArchived && jsonSchema.properties.is_deleted) {
        builder.where(`${modelClass.tableName}.is_deleted`, false);
      }
    });
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return BaseModelQueryBuilder;
  }
}

class Page extends BaseModel {
  static get tableName() {
    return 'page';
  }

  static get idColumn() {
    return 'page_id';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        page_id: {type: 'integer'},
        is_deleted: {type: 'boolean'}
      }
    };
  }

  static get relationMappings() {
    return {
      parents: {
        relation: Model.ManyToManyRelation,
        modelClass: Page,
        join: {
          from: 'page.page_id',
          through: {
            modelClass: PageRelationship,
            from: 'page_relationship.child_id',
            to: 'page_relationship.parent_id'
          },
          to: 'page.page_id'
        }
      },

      children: {
        relation: Model.ManyToManyRelation,
        modelClass: Page,
        filter: builder => builder.where('page_relationship.is_deleted', false),
        join: {
          from: 'page.page_id',
          through: {
            modelClass: PageRelationship,
            from: 'page_relationship.parent_id',
            to: 'page_relationship.child_id'
          },
          to: 'page.page_id'
        }
      }
    };
  }
}

class PageRelationship extends BaseModel {
  static get tableName() {
    return 'page_relationship';
  }

  static get idColumn() {
    return ['parent_id', 'child_id'];
  }
  
  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        parent_id: {type: 'integer'},
        child_id: {type: 'integer'},
        is_deleted: {type: 'boolean'}
      }
    };
  }
}

async function setupDb() {
  await knex.schema.dropTableIfExists('page_relationship');
  await knex.schema.dropTableIfExists('page');

  await knex.schema.createTableIfNotExists('page', table => {
    table.increments('page_id').primary();
    table.boolean('is_deleted').notNullable().defaultTo(false);
  });

  await knex.schema.createTableIfNotExists('page_relationship', table => {
    table.integer('child_id').references('page.page_id').index().onDelete('CASCADE');
    table.integer('parent_id').references('page.page_id').index().onDelete('CASCADE');
    table.boolean('is_deleted').notNullable().defaultTo(false);
  });
}

async function populate() {
  await Page.query().delete();
  await Page
    .query()
    .insertGraph({
      is_deleted: false,

      children: [{
        is_deleted: true,
      }, {
        is_deleted: false,
      }]
    });
}

async function test() {
  const result = await Page
    .query()
    .findById(1)
    .eager('children')
    .debug();

  console.log(result);
}

async function start() {
  await setupDb();
  await populate();
  await test();
}

start().then(() => knex.destroy());
```

**Comment by koskimas** [comment] 2017-06-21 15:55
And by the way, it __is__ `RelatedQueryBuilder` and not `QueryRelatedBuilder` as you said. It was a typo.

**Comment by koskimas** [comment] 2017-06-28 06:53
@allxie Were you able to solve this?

**Comment by koskimas** [comment] 2017-06-29 12:51
Closing again since nothing is happening..

**Closed by koskimas** 2017-06-29 12:51 UTC

**Comment by allxie** [comment] 2017-06-29 19:54
I did not solve it. ~~ Sorry for the late response. Needed to spend the time refactoring for a launch. Was still getting `invalid reference to FROM-clause entry`, or `is_deleted is ambiguous`

**Comment by wswoodruff** [comment] 2017-06-29 20:02
Ok, please let me know how it turns out

**Comment by jonathan-playvs** [comment] 2019-10-10 18:53
I'm having the same issue (Objection 1.6.9, Knex 0.16.5).

I have a relationship from `team` to `season` through a join table, `season_team`. I want the `season_team` relationship to be soft-deleted through a `deleted_at` column. However, when I specify `modify(builder) => builder.where({ 'season_team.deletedAt': null })`, it breaks the behavior of `joinRelation`. However, eager joins still work.

The problem is, the table `season_team` is being aliased to `teams:seasons_join`. Is there a more flexible way to reference the `season_team` table name that will "carry" any aliases created within the query? Thanks for your vigilance and generous support @koskimas ! (cc @allxie)

Here is the query:
```
User.query()
    .joinRelation('teams.seasons')
    .findById(USER_1_ID)
```

And the error:
```
select "user".* from "user" 
inner join "team_member" as "teams_join" on "teams_join"."user_id" = "user"."id" 
inner join (select "team".* from "team") as "teams" on "teams_join"."team_id" = "teams"."id" 
inner join "season_team" as "teams:seasons_join" on "teams:seasons_join"."team_id" = "teams"."id" 
inner join (select "season".* from "season" where "season_team"."deleted_at" is null) as "teams:seasons" on "teams:seasons_join"."season_id" = "teams:seasons"."id" where "user"."id" = $1 

- invalid reference to FROM-clause entry for table "season_team"
```

My relation mapping (In model `Team.ts`):
```
seasons: {
  modelClass: 'Season',
  relation: BaseModel.ManyToManyRelation,
  modify(builder) {
    return builder.where({
      [`${tableNames.seasonTeam}.deletedAt`]: null
    })
  },
  join: {
    from: `${tableNames.team}.id`,
    through: {
      modelClass: 'SeasonTeam',
      from: `${tableNames.seasonTeam}.teamId`,
      to: `${tableNames.seasonTeam}.seasonId`,
      extra: ['createdAt'],
    },
    to: `${tableNames.season}.id`,
  },
}
```

**Comment by jonathan-playvs** [comment] 2019-10-10 19:38
I have also tried using `tableNameFor(SeasonTeam)` and `tableRefFor(SeasonTeam)`, to no avail.

**Comment by jonathan-playvs** [comment] 2019-10-10 19:47
I have also tried using `tableNameFor(SeasonTeam)` and `tableRefFor(SeasonTeam)`, to no avail. @koskimas or @allxie , would you be willing to please re-open this issue?

**Comment by jonathan-playvs** [comment] 2020-08-13 22:14
Hey @koskimas , I think this issue is still relevant with the current version of Objection.
