### ISSUE TITLE
Custom ID types on eager queries

### ISSUE THREAD

**Issue by allistercsmith** [Vincit/objection.js#1368] opened 2019-06-08 11:03 UTC
Hey there :wave:

I have the following model definition:

```
class Foo extends Model {
  id: UUID;
  barId: UUID;

  static get tableName() {
    return 'foo';
  }

  $parseDatabaseJson(json: any) {
    json = super.$parseDatabaseJson(json);

    if (json.id && !(json.id instanceof UUID)) {
      json.id = UUID.fromString(json.id);
    }

    if (json.bardId && !(json.barId instanceof UUID)) {
      json.barId = UUID.fromString(json.barId);
    }

    return json;
  }

  $formatDatabaseJson(json: any) {
    json = super.$formatDatabaseJson(json);

    if (json.id && json.id instanceof UUID) {
      json.id = json.id.toString();
    }

    if (json.bardId && json.bardId instanceof UUID) {
      json.bardId = json.bardId.toString();
    }

    return json;
  }

  static get relationMappings() {
    return {
      bar: {
        relation: Model.BelongsToOneRelation,
        modelClass: Bar,
        join: {
          from: 'foo.barId',
          to: 'bar.id',
        },
      },
    };
  }
}
```

I have two questions.

Firstly, calling `await Foo.query().eager('bar')` fails as Postgres complains that `{"str":"3957295d-57cb-49ef-bc83-17054f7facf6"}` is an invalid `uuid` type. Seems like when fetching the `bar` relation, the `barId` value in `Foo` isn't being converted to a string, and is being passed as a `UUID` class instead. Should `$formatDatabaseJson` not be called first, or is there another way to handle type casting for relation queries?

Secondly, I [read](http://vincit.github.io/objection.js/api/model/instance-methods.html#parsedatabasejson) that `$parseDatabaseJson` can be called multiple times, with subsets of model values. However, it seems subsequent calls are made with the results of previous calls to `$parseDatabaseJson`. This means that on first run, it correctly casts `json.id` to a `UUID` type, but on second run, `json.id` is already a `UUID` type, and causes `UUID.fromString(json.id)` to fail. I therefore have to be very defensive in that function (i.e., add `if (json.id && !(json.id instanceof UUID))`). Is there a more elegant, less boiler-plate way of handling this?

Thanks for all the hard work!

**Comment by koskimas** [comment] 2019-06-08 12:43
Hi,

`$formatDatabaseJson` is not called for the foreign keys, but it probably should be for cases like this. The problem is that at this point, it would probably break too much existing code and projects in unpredicable ways. People use `$parseDatabaseJson` and `$formatDatabaseJson` in very different ways.

I'll take a look at some point to see if we could have some kind of cleaner solution for this problem.

In the meanwhile I'd suggest avoiding mapping foreign keys to class instances. Is is somehow particularly useful to have the ids as `UUID` instances? What's the benefit over just having them as strings?

**Comment by allistercsmith** [comment] 2019-06-08 13:14
Hey @koskimas 👋

Thanks for the quick response! That clears it up for me.

There’s no convincing reason for us to continue using the `UUID` wrapper. It just contains some generic UUID helpers (I.e., generating a random UUID), but those can very easily be split out. My biggest goal was to minimize the required changes to our existing codebase when introducing objection.js into the mix, but I can make it work.

Will keep an eye out for a fix, but feel free to close this issue in the interim.

Cheers 🙂

**Comment by koskimas** [comment] 2019-06-09 08:17
If `UUID` is a class you wrote yourself, you could add this method

```js
  toKnexRaw(builder) {
    return builder.knex().raw('?', this.toString());
  }
```

and thing should work. `toKnexRaw` is not part of the public API yet, but I'll add it soon(ish) and it should be safe to use it.

**Comment by koskimas** [comment] 2019-09-21 11:18
Actually, you shouldn't have a class instance as an `id`. It would be really difficult to make work with all objection features. I'll close this for now.

**Closed by koskimas** 2019-09-21 11:18 UTC
