### ISSUE TITLE
Support for knex 0.95.0

### ISSUE THREAD

**Issue by david-wb** [Vincit/objection.js#2012] opened 2021-03-04 18:30 UTC
I just upgrade knex to 0.95.0 and now I'm getting typescript compilation errors in objectionjs like this:

```
node_modules/objection/typings/objection/index.d.ts:1830:12 - error TS2709: Cannot use namespace 'Knex' as a type.

1830     (knex: Knex, modelClasses: AnyModelConstructor[]): Promise<void>;
                ~~~~
```

Will support for 0.95 be added soon?

**Comment by mrhitman** [comment] 2021-03-04 18:51
with 0.95.1  same problem

**Comment by koskimas** [comment] 2021-03-04 19:09
Supporting 0.95 means dropping support for all versions before. Knex has put us in quite of a pickle. It's better to not update to 0.95 for now.

**Comment by kibertoad** [comment] 2021-03-04 19:51
@koskimas I apologize for the problems caused by this change, but since we are starting to prepare for 1.0.0, it was important to lock in all the major breaking changes within 0.95.0 so that 1.0.0 is mostly uneventful with just last-minute lesser breaking changes included. And personally I find previous default exported type that could mean three different things, depending on a context, extremely confusing.
I take it that there are no plans for next Objection.js semver major in the nearby future?

**Comment by koskimas** [comment] 2021-03-07 10:32
Well, objection should have limited the range of accepted peer dependencies to knex. You did bump the largest nonzero version with the breaking change, which is in line with semver. Objection used to have a strict selector for accepted knex versions, but then I had to bump that like every week when a new knex version came out, so I changed it to `0.x`.

I don't want to bump the objection major version just for this though. I'll probably just bump the minor.

**Comment by kibertoad** [comment] 2021-03-07 10:52
I'll update the PR for 0.95 support then.

**Comment by Zeswen** [comment] 2021-03-12 14:10
If it's a breaking change, why wouldn't knex just go for 1.X.X?

**Comment by kibertoad** [comment] 2021-03-12 14:14
@Zeswen You can only have one 1.0.0 release ever, so our decision was to do as many big changes in 0.95.0 as possible and work out all the rough edges, so that 1.0.0 is as polished and as attractive to the wide audience as possible. I expect it to have much lesser amount of breaking changes.

**Comment by Zeswen** [comment] 2021-03-12 14:38
> @Zeswen You can only have one 1.0.0 release ever, so our decision was to do as many big changes in 0.95.0 as possible and work out all the rough edges, so that 1.0.0 is as polished and as attractive to the wide audience as possible. I expect it to have much lesser amount of breaking changes.

Thank you for your clarification, but I belive a better approach would have been possible :)

As the [semVer documentation](https://semver.org/) implies, a pre-release `1.0.0-beta` or `1.0.0-rc.1` would have been a great one for it.
Updating the minor versions breaks most of the packages that have automated minor/patch versions updates, its a great risk.

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by koskimas** [comment] 2021-03-13 09:56
After giving it some more thought, I'll just go ahead and do "the right thing" and release 3.0. @kibertoad Are you sure there will be no more breaking changes before 1.0? Because if there will, We'll have to wait until that. I don't want to release 4.0, 5.0 and 6.0 too just because of knex.

**Comment by kibertoad** [comment] 2021-03-13 10:29
@koskimas No more breaking changes in 0.95.0; next batch of breaking changes will be in 1.0.0, but hopefully none of them will be major enough to require changes on Objection side.

**Comment by kibertoad** [comment] 2021-03-13 10:29
I'll update the 0.95.0 compatibility PR in a few hours, sorry for the delay

**Comment by koskimas** [comment] 2021-03-13 15:28
@kibertoad Thank you so much for working on the PR. I really appreciate it!

> batch of breaking changes will be in 1.0.0

I'm afraid this means that we'll have to wait until 1.0 to release objection 3.0. I don't want to release 3.0 now to support > 0.95 < 1.0 and then 4.0 when knex 1.0 comes out 😞

**Comment by kibertoad** [comment] 2021-03-13 15:45
@koskimas Honestly, I believe 1.0.0 breaking anything in Objection to be extremely unlikely. We've released 7 major versions of knex in last 2 years, and I think that `0.95.0` was the first one to include changes that ended up to be breaking for Objection. I think the extent of breaking changes in knex are going to amount to dropping deprecated use-cases such as passing negative offset, which Objection shouldn't care about. The whole idea of `0.95.0` was to do all the scary changes prior to `1.0.0`.

**Comment by devinivy** [comment] 2021-03-13 17:59
If the period of time is going to be relatively short between v0.95 and the release of v1, I'd recommend we just wait!  What's the rush?  Then objection v3 can support v0.95+, or if there do end-up being breaking changes between v0.95 and v1 that affect objection, perhaps objection would just skip v0.95 or be able to offer some compatibility option.  I don't see any major downside, besides not being able to use v0.95 immediately which sounds like it's being used as a beta version of v1 anyway, and the upside is that objection users are protected from potential churn and confusion.  I feel pretty sure that if it had been released as a v1 beta, that is how it would be approached on the objection side.  I have been following this conversation, as I maintain schwifty which is a peer of objection.

**Comment by kibertoad** [comment] 2021-03-13 18:08
I doubt it's going to be short. My current estimate would be half a year to a year till 1.0.0.

**Comment by vladaman** [comment] 2021-03-15 05:18
@devinivy We are starting new project, which combination of versions would you suggest to use?

**Comment by koskimas** [comment] 2021-03-15 11:54
@vladaman The newest objection version supports knex < 0.95. So I'd use the latest objection and the highest knex < 0.95

**Comment by vladshcherbin** [comment] 2021-03-21 07:39
According to previous knex 1.0 plans, it's reasonable to release 0.95 support in 3.0.
Knex major release may happen in a few years and it'll be nice to use 0.95 in objection until then.

**Comment by koskimas** [comment] 2021-03-21 17:21
Was there something critical released with knex 0.95? Is there a compelling reason for people to update to knex 0.95? If there was no major bug fixes or new features, I don't see the point in releasing 3.0 just for 0.95 - 1.00 and I agree with @devinivy that we should just wait.

**Comment by kibertoad** [comment] 2021-03-21 17:26
@koskimas There were drastical improvements to MSSQL support and plenty of new stuff for SQLite, and overall it was probably the most improvement-packed major version in the last three years.
If that would make you more comfortable to release 3.0 earlier, I can personally promise that there will be no changes that would be breaking for Objection.js in 1.0.0, and if there end up being any, I would revert them.

**Comment by koskimas** [comment] 2021-03-22 13:38
@kibertoad Sounds great! Thank you. I'll move forward with the release of 3.0 then.

**Comment by JaneJeon** [comment] 2021-03-29 10:32
Ohhhhh, sh*t, things are happening! @koskimas is Objection3 going to be just a semver update to accomodate knex0.95/1 or do you see making other breaking changes as well (or using this opportunity to add/drop some features)?

**Comment by kibertoad** [comment] 2021-03-29 10:56
There were at least two other breaking changes mentioned that are likely to be included in this window as well.

**Comment by JaneJeon** [comment] 2021-03-29 11:35
@kibertoad for knex or objection3?

**Comment by kibertoad** [comment] 2021-03-29 11:37
Objection. To quote koskimas:
"I'll also get the chance to fix #1651 and #1689 at the same time, both of which require breaking changes."

**Comment by anish-techpro** [comment] 2021-04-19 19:38
> Sounds great! Thank you. I'll move forward with the release of 3.0 then.

@koskimas what is the ETA for objection 3.0? and should we continue development with the following combination as of now?

```
"knex": "^0.95.2",
"objection": "^2.2.15"
```

**Comment by devinivy** [comment] 2021-04-19 19:46
@anish-techpro my understanding is that we should stick with knex v0.21.x when using objection v2.  This is now reflected in objection's peer dependencies.  Once objection v3 is released then knex 0.95 and eventually knex v1 will be on the table.

**Comment by koskimas** [comment] 2021-04-23 12:59
@AnianZ There's no ETA unfortunately. It'll happen when I find couple of days of spare time to do work on objection.

**Comment by thefoxie** [comment] 2021-05-05 20:37
Is there something broken with the newer knex? I got it in my project and everything seems to be working. 🤷

**Comment by koskimas** [comment] 2021-05-06 06:37
@thefoxie I think it's mostly the typings that are incompatible.

**Comment by capaj** [comment] 2021-06-08 13:34
@koskimas is there a WIP branch for objection 3.0? If there was, I'd love to take a peek at those typings and try my best to get them fixed.

**Comment by kibertoad** [comment] 2021-06-08 13:49
@capaj Typings are fixed in https://github.com/Vincit/objection.js/pull/1992, you can use that branch.

**Comment by koskimas** [comment] 2021-07-16 10:39
I'll soon release the first alpha version of objection 3. It supports the newest knex. To install it, run `npm install objection@next`

**Comment by kibertoad** [comment] 2021-07-16 10:59
@koskimas Are you open to introducing additional breaking changes during the alpha phase of Objection 3, or it's API-frozen already?

**Comment by koskimas** [comment] 2021-07-16 11:35
@kibertoad The API is not frozen yet. I'll be implementing multiple breaking changes in the near future. The first RC should be frozen.

**Comment by Naragod** [comment] 2021-07-23 15:13
Any updates on this?

**Comment by koskimas** [comment] 2021-07-27 09:57
@kibertoad do you have any timeline for these breaking changes? Or did you mean knew will have them or do you have something for objection directly?

**Comment by kibertoad** [comment] 2021-07-27 10:00
@koskimas I've been considering landing https://github.com/knex/knex/pull/4471 for the next semver major, I don't think I have anything else scheduled yet. Do you expect this to require adjustments on Objection side as well?

**Comment by koskimas** [comment] 2021-07-27 14:33
That should't affect objection. Objection already always returns model instances.

**Comment by ibratoev** [comment] 2021-08-01 08:05
One more thing that would be great to support from the new version of knex - transactions for MySQL: https://github.com/knex/knex/pull/4185

**Comment by DominikSerafin** [comment] 2021-08-30 15:49
@koskimas is there any changelog for objection@3? I've checked https://vincit.github.io/objection.js/release-notes/changelog.html, but it only documents changes up to objection@2.2.10. 

I would like to start using knex@0.95 with objection@3, but I don't know how to migrate from objection@2.

**Comment by andersevenrud** [comment] 2021-08-30 16:35
@DominikSerafin That one doesn't seem up-to-date. There's also a tag missing here on Github.

So I guess you'll have to use the compare feature for now: https://github.com/Vincit/objection.js/compare/2.2.13...3.0.0-alpha.3

**Comment by HappyZombies** [comment] 2021-09-27 15:39
Any update on this? What are the risks exactly if use 0.95.x > ? Are these TypeScript only issues?

**Comment by kibertoad** [comment] 2021-09-27 15:40
> Are these TypeScript only issues?

Yes.

**Comment by koskimas** [comment] 2021-09-28 16:31
I'll comment here as soon as there is something to comment. No need for these "any updates on this" messages.

**Comment by koskimas** [comment] 2021-11-05 22:53
I just released the first 3.0 RC version. The release is just around the corner.

**Comment by JaneJeon** [comment] 2021-11-05 23:05
Will be looking forward to the release notes!

**Comment by koskimas** [comment] 2021-11-09 19:44
@JaneJeon You can see the initial release notes [here](https://github.com/Vincit/objection.js/blob/master/doc/release-notes/migration.md)

**Comment by koskimas** [comment] 2021-11-09 19:57
Objection 3.0 is now released.

**Closed by koskimas** 2021-11-09 19:57 UTC

**Comment by koskimas** [comment] 2021-11-09 20:04
https://vincit.github.io/objection.js/release-notes/changelog.html

**Comment by JaneJeon** [comment] 2021-11-09 20:36
Awesome work, thank you for this release! @koskimas

**Comment by wafaboussada** [comment] 2021-12-13 14:44
Hello 
when updating objection to 3.0.0 and knex to 0.95.14, i got this error : type must be JSONType or JSONType[]: date.
and there are warnings in node modules objection

**Comment by thefoxie** [comment] 2021-12-14 07:05
@wafaboussada this is probably related https://github.com/Vincit/objection.js/issues/2142#issuecomment-966195160
