### ISSUE TITLE
Timestamps in a base class

### ISSUE THREAD

**Issue by anyong** [Vincit/objection.js#110] opened 2016-04-13 09:16 UTC
My model classes all extend from a base class. I would like a simple `static timestamps = true;` to automatically add the timestamps to `created_at` and `updated_at` as appropriate for insert and update queries, and also to add `created_at` and `updated_at` to `jsonSchema` so that it passes validation. I can't get it working. Currently I have something like this:

```js
class BaseModel extends objection.Model {
    $beforeValidate (jsonSchema, json, opt) {
        if (this.constructor.timestamps) {
            jsonSchema.properties.created_at = {type: 'string'};
            jsonSchema.properties.updated_at = {type: 'string'};
        }

        return jsonSchema;
    }

    $beforeInsert () {
        if (this.constructor.timestamps) {
            const now = new Date().toISOString();
            this.created_at = now;
            this.updated_at = now;
        }
    }

    $beforeUpdate () {
        if (this.constructor.timestamps) {
            const now = new Date().toISOString();
            this.updated_at = now;
        }
    }
}

class MyModel extends BaseModel {
    static timestamps = true;
}
```

I've tracked down the problem to `toKnexInput`, which calls `$toDatabaseJson`, which is looking at the original `jsonSchema` as opposed to the modified version returned from `beforeValidate`. What's the point of being able to output a new `jsonSchema` from `$beforeValidate` if `$toDatabaseJson` (and presumably other methods) ignore it?

**Comment by koskimas** [comment] 2016-04-13 10:22
This is clearly a bug in objection. The problem is that objection `Model` omits all properties that are not listed in `jsonSchema`. This is something it probably shouldn't do, or at least there should be an option to turn this off.

I'll try to figure out a fix for this. In the mean time you are left wit two options:

1. add `created_at` and `updated_at` to each model's `jsonSchema`
2. Use this hack in the base model:

```js
$toDatabaseJson() {
  const omit = this.constructor.getRelations();
  return this.$$toJson(true, omit, null);
}
```

**Comment by anyong** [comment] 2016-04-13 11:11
Great, that override works perfectly for now anyway until this gets fixed!

**Comment by haywirez** [comment] 2016-04-14 09:34
Have been using option 1, I think this somehow makes sense as your models' `jsonSchema` should reflect the table columns completely.

**Closed** 2016-08-28 13:13 UTC
Labels: bug
