### ISSUE TITLE
`raw` seems to be returning invalid SQL

### ISSUE THREAD

**Issue by ZakFahey** [Vincit/objection.js#900] opened 2018-05-02 21:34 UTC
In my project I have a query which contains this code:
```
.innerJoin('configs as default_conf', function() {
    this.on('manufacturers.id', 'default_conf.manufacturer')
        .andOn(raw('(SELECT is_global_organization from organizations where id = default_conf.organization) = TRUE'));
})
```
I'd expect this to output valid SQL code, but this is what's outputted:
```
inner join "configs" as "default_conf"
  on "manufacturers"."id" = "default_conf"."manufacturer"
     and "_sql" = "SELECT is_global_organization from organizations where id = default_conf"."organization = TRUE"
     and "_args" =
```
Instead of using the raw select statement, Objection checks if "_sql" is equal to the raw query, and then I see "_args" which is completely empty and makes an incomplete statement which throws an error.

It's configured for Postgres, by the way.

**Comment by koskimas** [comment] 2018-05-02 22:25
There is a file called `reproduction-template.js` in the repo root that you can use as a starting point if you want.

**Comment by koskimas** [comment] 2018-05-02 22:34
One thing that has been causing things like this in the past is having two different versions of knex being used with the same objection code, but that should be fixed now. I'm assuming you are running the latest version of objection since you didn't mention it?

**Comment by ZakFahey** [comment] 2018-05-03 19:33
I tried duplicating the bug in the production template, but things did work correctly when I did that.

And both knex and objection are both up-to-date at versions 0.14.6 and 1.1.7 respectively.

**Comment by koskimas** [comment] 2018-05-03 19:38
Weird... As a workaround you should be able to use `knex.raw` instead of `objection.raw`. I'll try some things if I can reproduce this.

**Comment by koskimas** [comment] 2018-05-03 21:45
I can't seem to reproduce this no matter what I try.  I'll reopen this if you can reproduce this.

**Closed by koskimas** 2018-05-03 21:45 UTC
Labels: needs more info
