### ISSUE TITLE
aliasFor not working when used with query()

### ISSUE THREAD

**Issue by patrikwalker** [Vincit/objection.js#1957] opened 2020-12-30 18:52 UTC
Hi,

I stumbled upon an issue with `aliasFor`, it doesn't seem to work when used with a query directly, like described in the [docs](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#aliasfor). But everything seems to work fine if used with `$relatedQuery`.

I used the reproduction template to test it (I added an extra property named `someProp`):

```
const jennifer = await Person.query().findOne({ firstName: 'Jennifer' });

// this works fine
const jenniferMovies = await jennifer
  .$relatedQuery('movies')
  .aliasFor('Person_Movie', 'pm')
  .where('pm.someProp', 100);

// this doesn't alias Person_Movie correctly and throws an error because pm is not known
const jenniferWithMovies = await Person.query()
  .findOne({ firstName: 'Jennifer' })
  .aliasFor('Person_Movie', 'pm')
  .joinRelated('movies')
  .where('pm.someProp', 100);
```

This also explains why the test pass: They only test for the case with the `$relatedQuery`.

This should be working, or am I missing something?

**Comment by ramos-ph** [comment] 2021-05-13 19:14
Hey, there is any update on this one?
I were able to reproduce the problem and I'm investigating what the cause might be.
I'll open a PR to fix this when I find what is causing the issue.

**Comment by lehni** [comment] 2023-04-15 08:10
Fixed and merged, finally! 🎉

**Closed by lehni** 2023-04-15 08:10 UTC
Labels: bug
