### ISSUE TITLE
Paging not working with withGraphJoined()

### ISSUE THREAD

**Issue by prasoon007** [Vincit/objection.js#2329] opened 2022-10-19 07:36 UTC
hello
I have Users model with several child models and later on i have filters on these child models and also i am trying to paginate the result but when i am trying to join the relations with withGraphJoined paging is not working.

`    
     query.withGraphJoined(
        {
          creatorDetails: {
            workCategoryDetails: true,
            languageDetails: {
              language: true
          },
        },
        { aliases: { creatorDetails: 'creator' } },
      )
`
1. creatorDetails is HasOneRelation
2. workCategoryDetails is HasOneRelation
3. languageDetails is HasManyRelation

**Comment by lehni** [comment] 2023-04-15 08:00
Closing as a duplicate of #2186

**Closed by lehni** 2023-04-15 08:00 UTC
Labels: bug
