### ISSUE TITLE
Add filter method on ManyToMany join table.

### ISSUE THREAD

**Issue by keepcosmos** [Vincit/objection.js#1356] opened 2019-05-29 15:12 UTC
Is there any way to add `filter` options on ManyToMany `through`?

like,

```js
goodFriends: {
  relation: ManyToManyRelation,
  to: XX,
  from: YY,
  through: {
    from: 'XX.id'
    to: 'YY.id',
    filter: (builder) => { builder.where('relationships.type', 'good') }
  }
}
```

**Comment by koskimas** [comment] 2019-05-30 19:28
Not currently, but that could be useful addition. It could be useful solution to https://github.com/Vincit/objection.js/issues/837

**Comment by ericmuyser** [comment] 2019-06-20 06:00
This would allow `N:M` polymorphic relationships like in this answer: https://github.com/Vincit/objection.js/issues/19#issuecomment-389356230

But instead of the filter field being on the relation table, it would be on the join table, which is freaking awesome (and how I thought it worked until I kept running into this error and analyzed that answer further).

I have a generic exclusive arc table that allows me to build relationships on the fly. I put the `extra: ['relationKey']` on that table thinking it would work. It doesn't. So I'll need a `relationKey` on every single table. Sigh.

![image](https://user-images.githubusercontent.com/156768/59824461-1df72d00-936c-11e9-9a9b-001cc807d0eb.png)

**Comment by ericmuyser** [comment] 2019-07-16 07:59
I figured out how to the querying part, but I still need to set a value on the pivot table column for querying later. (Mentioned in #1405)

The problem is beforeInsert isn't executed below, because it's not inserting a new profile. But it is inserting a new pivot table row for the relation, which is where I need to set a column value.


```
    public static get relationMappings (): RelationMappings {
        return {
            owner: {
                relation: Model.HasOneThroughRelation,
                modelClass: Profile,
                filter: (qb) => {
                    qb.join('nodes as node_profiles', 'node_profiles.toProfileId', '=', 'profiles.id')
                    qb.where('node_profiles.relationKey', 'owner')
                },
                beforeInsert (model) {
                    (model as Node).relationKey = 'owner'
                },
                join: {
                    from: 'collections.id',
                    to: 'profiles.id',
                    through: {
                        from: 'nodes.fromCollectionId',
                        to: 'nodes.toProfileId'
                    }
                }
            }
        }
    }
```

**Comment by lexa0303** [comment] 2020-06-03 10:04
Any updates on this?

**Comment by haydernativapps** [comment] 2020-10-22 00:40
Any update about this issue?

**Comment by sayhicoelho** [comment] 2020-11-30 21:58
Any update? This feature is needed...

**Comment by bbrizzi** [comment] 2021-01-13 10:35
I found a workaround by defining the intermediary table in my models and aliasing the fields using virtual attributes.

I have a polymorphic N:M relationship between Devices and Configurations through a ConfigurationLink pivot table.

In /models/ConfigurationLink :
```
      config: {
        relation: Model.HasOneRelation,
        modelClass: Configuration,
        join: {
          from: 'configuration_links.configuration_id',
          to: 'configurations.id'
        }
      },
```

In /models/Device.js :
```
      config_link: {
        relation: Model.HasManyRelation,

        modelClass: ConfigurationLink,

        join: {
          from: "devices.id",
          to: "configuration_links.configurable_id",
        },

        filter (builder) {
          // Filter for polymorphic relationship
          builder.where("configurable_type", "device");
          builder.where("configuration_links.deleted", false);
        }
      },
```

And :

```
  static get virtualAttributes() {
    return ['config'];
  }

  config() {
    return this.config_link.map((cl) => (
        {
        ...cl.config,
       premium: cl.premium, // Extra field fetched from the pivot table
       })
    );
  }
```

**Comment by lehni** [comment] 2023-04-16 20:07
Fixed in #1356

**Closed by lehni** 2023-04-16 20:07 UTC
Labels: enhancement

**Comment by developer239** [comment] 2024-04-01 17:41
It doesn't work. Both. filter and modify is ignored.

**Comment by danlobo** [comment] 2024-07-19 15:16
Found the issue.

`Relation.clone()` does not copy `joinTableModify`, resulting in the property being missing when the model binds to Knex. Consequently, `filter` and `modify` are not applied.

To fix this, add:

`relation.joinTableModify = this.joinTableModify;`

to Relation.clone(). The version of Objection.js tested is 3.1.4.

Example:

```
94:    relation.joinTableModelClass = this.joinTableModelClass;
95:    relation.joinTableOwnerProp = this.joinTableOwnerProp;
96:    relation.joinTableModify = this.joinTableModify;    // Add this line
97:    relation.joinTableRelatedProp = this.joinTableRelatedProp;
98:    relation.joinTableBeforeInsert = this.joinTableBeforeInsert;
99:    relation.joinTableExtras = this.joinTableExtras;
```
