### ISSUE TITLE
upsertGraph(), upsert one association and unrelate another one

### ISSUE THREAD

**Issue by beworker** [Vincit/objection.js#522] opened 2017-09-25 21:43 UTC
Hey, I have the following simple model:

```
 class Asset extends Model {
    static get tableName() { return 'Asset' }

    static get jsonSchema() {
        return {
            type: 'object',
            properties: {
                id: { type: 'integer' },
                parentId: { type: 'integer' },
                title: { type: 'string' }
        }
    }

    static get relationMappings() {
        return {
            parent: {
                relation: Model.BelongsToOneRelation,
                modelClass: Asset,
                join: {
                    from: 'Asset.parentId',
                    to: 'Asset.id'
                }
            },
            children: {
                relation: Model.HasManyRelation,
                modelClass: Asset,
                join: {
                    from: 'Asset.id',
                    to: 'Asset.parentId'
                }
            }
    }
}
```

Firstly I execute `upsertGraph()` like this (step 1)

```
Asset.query(trx).upsertGraph({
    title: 'this',
    parent: {
       title: 'parent'
    },
    children: [{
        title: 'child 1'
    }]
})
```
and it creates required structure. Then I try to change the children (remove 'child 1' and add 'child 2') and unrelate the parent by keeping the parent asset in the database (step 2). I tried to do it like this

```
Asset.query().upsertGraph({
    parent: null,
    children: [{
        title: 'child 2'
    }]
})
```

But it fails with the following error

```
insert into `Asset` (`parentId`, `title`) values (167, 'Chapter 3') - Cannot add or update 
a child row: a foreign key constraint fails (`test-db`.`asset`, CONSTRAINT 
`asset_parentid_foreign` FOREIGN KEY (`parentId`) REFERENCES `Asset` (`id`) 
ON DELETE CASCADE)

Error: Cannot add or update a child row: a foreign key constraint fails (`test-db`.`asset`,
 CONSTRAINT `asset_parentid_foreign` FOREIGN KEY (`parentId`) REFERENCES 
`Asset` (`id`) ON DELETE CASCADE)
```

ID 167 is a valid ID of `this` asset created at the step 1.
The calls are wrapped with transactions. I omitted them for sake of simplicity.

Am I doing anything wrong? Is there a way to unrelate parent using `upsertGraph` for this model?
Thanks in advance!

MySQL 5.7.11, Objection.js 0.8.9

**Comment by koskimas** [comment] 2017-09-25 22:00
Unfortunately you cannot mix unrelate/relate and delete/insert in the same `upsertGraph` query at the moment. I have no idea what is causing that error and it's pretty impossible for me to debug it with this information. The queries you wrote here are missing an id for the root object, `{unrelate: true}` option etc. I cannot know what is failing without seeing your __actual__ code.

Since you are trying to unrelate a parent object, you can simply set `parentId` to null. That's what the `unrelate` operation does.

```js
Asset.query().upsertGraph({
    id: 167,
    parentId: null,
    children: [{
        title: 'child 2'
    }]
})
```

If that doesn't help, could you try to write a reproduction of the bug that I can easily run and debug?

**Comment by beworker** [comment] 2017-09-26 14:01
Thanks for looking into the report, Sami. I forked https://github.com/beworker/objection.js and added a tests/integration/misc/#522.js test reproducing the issue.

**Comment by koskimas** [comment] 2017-09-26 14:41
I think the test fails because of `onDelete('CASCADE')`: The parent gets deleted, which causes the the child to get also deleted. Then the algorithm attempts to add a child for the row that already has been deleted. This works:

```js
'use strict';

const _ = require('lodash');
const expect = require('expect.js');
const Model = require('../../../').Model;

module.exports = (session) => {

  describe.only('Relate/unrelate question #522', () => {

    class Asset extends Model {
      static get tableName() {
        return 'Asset';
      }

      static get jsonSchema() {
        return {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            parentId: { type: 'integer' },
            title: { type: 'string' }
          }
        }
      }

      static get relationMappings() {
        return {
          parent: {
            relation: Model.BelongsToOneRelation,
            modelClass: Asset,
            join: {
              from: 'Asset.parentId',
              to: 'Asset.id'
            }
          },
          children: {
            relation: Model.HasManyRelation,
            modelClass: Asset,
            join: {
              from: 'Asset.id',
              to: 'Asset.parentId'
            }
          }
        }
      }
    }

    before(() => {
      return session.knex.schema
        .dropTableIfExists('Asset')
        .createTable('Asset', table => {
          table.increments('id').primary();
          table.integer('parentId').unsigned().references('id').inTable('Asset').onDelete('SET NULL');
          table.string('title');
        });
    });

    after(() => {
      return session.knex.schema.dropTableIfExists('Asset');
    });

    it('UpsertGraph should insert and update the graph', () => {
      return Asset
        .query(session.knex)
        .upsertGraph({
          title: 'this',

          parent: {
            title: 'parent'
          },

          children: [{
            title: 'child 1'
          }]
        })
        .then(graph => {
          return Asset
            .query(session.knex)
            .findById(graph.id)
            .eager('[parent, children]')
        })
        .then(graph => {
          return Asset
            .query(session.knex)
            .debug()
            .upsertGraph({
              id: graph.id,

              parent: null,

              children: [{
                title: 'child 2'
              }]
            })
            .then(updatedGraph => ({
              graph,
              updatedGraph
            }));
        })
        .then(({ graph, updatedGraph }) => {
          //console.log(graph)
          //console.log(updatedGraph)
        });
    });

  });

};
```

**Comment by koskimas** [comment] 2017-09-26 14:51
`parent` gets updated (as it should) because you don'r have `{unrelate: true}` option. But if you use that option, the `child 1` also gets unrelated and not deleted. As I mentioned in the original answer, you cannot currently use the delete and unrelate strategies in a single query. But as I also mentioned, if you want to unrelate a `BelongsToOneRelation` you can simply set the relation column to null (which is exactly the same thing).

```js
'use strict';

const _ = require('lodash');
const expect = require('expect.js');
const Model = require('../../../').Model;

module.exports = (session) => {

  describe.only('Relate/unrelate question #522', () => {

    class Asset extends Model {
      static get tableName() {
        return 'Asset';
      }

      static get jsonSchema() {
        return {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            parentId: { type: ['null', 'integer'] },
            title: { type: 'string' }
          }
        }
      }

      static get relationMappings() {
        return {
          parent: {
            relation: Model.BelongsToOneRelation,
            modelClass: Asset,
            join: {
              from: 'Asset.parentId',
              to: 'Asset.id'
            }
          },
          children: {
            relation: Model.HasManyRelation,
            modelClass: Asset,
            join: {
              from: 'Asset.id',
              to: 'Asset.parentId'
            }
          }
        }
      }
    }

    before(() => {
      return session.knex.schema
        .dropTableIfExists('Asset')
        .createTable('Asset', table => {
          table.increments('id').primary();
          table.integer('parentId').unsigned().references('id').inTable('Asset').onDelete('SET NULL');
          table.string('title');
        });
    });

    after(() => {
      return session.knex.schema.dropTableIfExists('Asset');
    });

    it('UpsertGraph should insert and update the graph', () => {
      return Asset
        .query(session.knex)
        .upsertGraph({
          title: 'this',

          parent: {
            title: 'parent'
          },

          children: [{
            title: 'child 1'
          }]
        })
        .then(graph => {
          return Asset
            .query(session.knex)
            .findById(graph.id)
            .eager('[parent, children]')
        })
        .then(graph => {
          return Asset
            .query(session.knex)
            .debug()
            .upsertGraph({
              id: graph.id,

              parentId: null,

              children: [{
                title: 'child 2'
              }]
            })
            .then(updatedGraph => ({
              graph,
              updatedGraph
            }));
        })
        .then(({ graph, updatedGraph }) => {
          //console.log(graph)
          //console.log(updatedGraph)
        });
    });

  });

};
```

**Comment by beworker** [comment] 2017-09-26 16:32
I see your point. This is kind of what I would like to achieve. My intention was to always *remove children* and *unrelate parents*. On delete cascade ensured that all sub-children are also property removed.

Would it make sense to have a capability to define a relation strategy per model (and maybe even per request)? Then in relational mapping I would say something like this.

```
static get relationMappings() {
        return {
          parent: {
            relation: Model.BelongsToOneRelation,
            relationStrategy: {
                relate: true,
                unrelate: true
            }
            ...
          },
          children: {
            relation: Model.HasManyRelation,
            relationStrategy: {
                relate: false,
                unrelate: false
            }
          }
        }
      }
```
What do you think?

**Comment by koskimas** [comment] 2017-09-26 17:22
I don't know about defining the upsert options in the relations but I have been thinking about something like this:

```js
Person
  .query()
  .upsert(theUpsert, {
    // true/false of a list of relation paths that should get related.
    relate: [
      'parent',
      'children.parent.children.movies.blaa'
    ],
    unrelate: [
      'parent'
    ]
  });
```

**Comment by koskimas** [comment] 2017-09-26 18:08
If you read the original version of the previous message, please read it again 😄 It had 100 confusing typos.

**Comment by beworker** [comment] 2017-09-26 19:09
Now I'm curious how the version with "100 confusing errors" looked like ;) I like the option you proposed too. It will give us more flexibility in choosing the desired behavior in respect of "insert or relate". If you decide to implement it, do you need any help?

Off-topic. In my last project I was using sequelize and I have to mention I like objection waaaay better. In my opinion it is very close to how SQL shall be used nowadays. Kudos for your job.

**Comment by koskimas** [comment] 2017-09-26 23:34
Thank you for the compliments, I really appreciate them!

Help is usually welcome, but in this case It's probably a lot easier if I implement it. Thank you for the offer! `upsertGraph` is the most complex part of objection and it took me forever to get it done. So even if you are a supercoder from outer space, it would take you some time and multiple WTF:s to contribute to that part of objection 😄 The fact that test coverage of `upsertGraph` isn't that good yet doesn't help.

I'll add this feature to my todo list.

**Comment by beworker** [comment] 2017-09-27 09:54
That makes sense. 

I added and pushed a `ManyToManyRelation` relation to the test, which shall always be unrelated instead of deleted. In case you need it for testing. I would be happy to test the feature once it's implemented 👍

**Comment by koskimas** [comment] 2017-09-27 22:16
@beworker First draft of the feature is now implemented [in a branch](https://github.com/Vincit/objection.js/tree/upsertGraph-partial-relate) if you want to test it. Everything __should__ work, but haven't tested it much yet.

**Comment by beworker** [comment] 2017-09-29 14:01
@koskimas Wow, that was fast :)

I [forked you branch](https://github.com/beworker/objection.js/tree/upsertGraph-partial-relate) and added the [test 522](https://github.com/beworker/objection.js/blob/upsertGraph-partial-relate/tests/integration/misc/%23522.js) to it. Used options look like this

```
{
    relate: ['parent', 'genres'],
    unrelate: ['parent', 'genres']
}
```
I interpret it like this: `parent` and `genres` relations shall be related/unrelated and the other relations (`children` in my case) shall be added/removed. Is this correct?

The test fails with
```
Error: {
  "parentId": [
    {
      "message": "should be integer",
      "keyword": "type",
      "params": {
        "type": "integer"
      }
    }
  ]
}
```

Hope this will help to investigate on this error.

**Comment by koskimas** [comment] 2017-09-29 21:15
I don't have time to test that right now, but you seem to be using `#dbRef` instead of `id` when relating. That probably should work though, but you could try it with `id`.

The error is a validation error. You have `parentId: { type: 'integer' }` which prevents null values. You should probably use `parentId: { type: ['null', 'integer'] }` since clearly you must be able to create Assets without a parent.

**Comment by beworker** [comment] 2017-09-30 08:14
@koskimas My bad. It works as expected. 

I've seen another related request #526 and gave some thoughts on it too because I have similar requirements. Maybe a configuration can look like this:

1. Define a type of relation in the model (`contain` or `refer`). A relation of `contain` type  adds/removes and a relation of `refer` type relates/unrelates models. Default values can be `contain`.
2. Define a strategy per relation path when calling `upsertGraph()` method call by choosing one one: `insert` - to add/relate given models, `delete` - to remove/unrelate given models or `replace` - to remove/unrelate existing and add/relate given models. Default value can be `replace`.

This might be not the most flexible solution, but it is very clean from understanding and control point of view. At least I would exactly know what and where I have to configure and how it behaves at runtime. What do you think?

**Comment by koskimas** [comment] 2017-10-20 15:56
@beworker Please comment on the relevant issue. I'm closing this one as it seems solved.

**Closed by koskimas** 2017-10-20 15:56 UTC
Labels: enhancement
