### ISSUE TITLE
Question: Best way to use Model hooks for an event bus?

### ISSUE THREAD

**Issue by sripberger** [Vincit/objection.js#2107] opened 2021-09-15 20:08 UTC
Greetings! I'm the tech team lead for an app called [Vurvey](https://vurvey.co). Our server team uses Objection as our ORM, and we're big fans. It's helped us get a lot done very quickly with with minimal issues.

At the moment I'm running into a bit of a problem that I'm hopeful maybe someone in the community might be able to help with. We're looking to implement real-time collaboration functionality and a bunch of other complex features that could be served very well by a queue-based event bus, where we can define subscribers to do background processing in response to arbitrary events by pulling event data out of a Redis-based queue.

Our situation right now is that we have a bunch of GraphQL mutation resolvers-- some of which are simple and only change one record, others are fairly complex and can change multiple records, and I'd like to avoid having to explicitly code every event that should go into our event queue for every resolver. I've been hoping I could resolve this by just overriding `$afterUpdate`, `$afterInsert`, and `$afterDelete` in our base model class, using these to identify the records that have changed and place events for these changes onto our event queue. The issue, however, is that the vast majority of our write operations take place inside [PostgreSQL Serializable or Repeatable-Read transactions](https://www.postgresql.org/docs/9.5/transaction-iso.html). These require us to retry on serialization failure, and even without retries may produce transactions which fail to commit *after* the model hooks have already been invoked.

It seems to me that this will inevitably produce repeated events, orphaned events, and other events ending up on the queue that shouldn't be there. It also means that, unless we put a substantial (and kludgy) delay on event job execution, we face the real possibility of real-time notifications being sent out for changes that have not yet committed to the database.

At the moment I'm kind of stuck on how to deal with all this. We could just design our event bus-- and the features which depend on it-- to be idempotent. This could deal with repetition, but it wouldn't deal with events for things that outright failed to commit. Another possibility I'm considering is wrapping our transactions with some additional logic, where we can hold events in memory until the transaction has committed, and then put them onto our queue *after* commit. I'm not entirely sure if this approach will even be possible, but if it is, I imagine it'd be something like using the Model hooks to put event data into an in-memory cache keyed by transaction id, then checking this cache and queuing up events *after* committing each transaction. This seems promising, but Knex transaction objects don't seem to have any way of accessing the transaction id. If they do, it isn't documented [here](https://knexjs.org/#Transactions), or in @types/knex for that matter.

So I'm a bit at a loss for what to do, now. I imagine that I am not the only person trying to do something like this, so I'm hoping maybe someone can point me in the right direction?

Thanks ahead of time!

**Comment by devinivy** [comment] 2021-09-15 20:19
I have approached a similar issue in the past by patching knex's transaction object `trx` so that `trx.commit()` method causes `trx` to emit a `'commit'` event on success.  I have used this, for example, to index updates to a search database only when those updates are successful.  Usually this hasn't implicated my objection models, however, because I handle this in my business/service layer rather than at the db/model layer.

However, I am a big fan of objection's static hooks, and they also can help access the relevant transaction and full result sets.  [Here's](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks) a guide on the static hooks, and [here](https://vincit.github.io/objection.js/api/types/#type-statichookarguments) are the arguments it receives.  Will be interested to hear what you land on if you find a good solution for you!

**Comment by laurisvan** [comment] 2021-09-17 14:15
We currently have the strateg you describe, and simply delay posting to Redis until the transaction has been committed. This was done by having a custom Transaction class that wraps the Objection/Knex transaction, and it can be awaited by saying waitUntilCommitted().

While this technically could be done and might be the fastest way to get something that runs, I would advice against doing that. The problem is that the solution practically blocks us from doing batch operations (we would not have handles to model instances), and with the traffic we receive it is a major hurdle. Another problem is that it puts such side effects way too deep layers, and makes things a bit hard to understand.

We are refactoring our system towards accepting that such functionality is better served in business logic rather than model layer, and we want to keep models super simple. In our (GraphQL derived) API we have simple service classes for the business logic part, and as long as we won't bypass the services, things will stay in control.

**Closed** 2021-09-19 08:36 UTC
