### ISSUE TITLE
Insert single row gets array back in typings

### ISSUE THREAD

**Issue by tomasfrancisco** [Vincit/objection.js#1372] opened 2019-06-13 12:34 UTC
I'm trying to insert a single row, but the typings are resulting in array.

<img width="312" alt="Screenshot 2019-06-13 at 13 57 56" src="https://user-images.githubusercontent.com/4301103/59432286-3fde3600-8de7-11e9-8410-2eb5859ef49f.png">
<img width="512" alt="Screenshot 2019-06-13 at 13 58 05" src="https://user-images.githubusercontent.com/4301103/59432601-02c67380-8de8-11e9-862b-b2f6c9da58ef.png">

Is there any way I can get a `User` instead of `User[]` back?
Even if I try to cast the result I get cast incompatibilities because of QueryBuilder.

**Comment by tomasfrancisco** [comment] 2019-06-17 09:03
I didn't have time yet to dig into this issue, but I just noticed the method `insertAndFetch` works like a charm.  
It infers the right returning type depending if the param is an array or object.

**Comment by javanotti** [comment] 2019-08-04 15:32
If all you got to return is the correspondent object for the row you just inserted you chould simply omit the `returning("*")`, especially if you are returning all columns. This looks like expected behavior to me, as described in [](http://knexjs.org/#Builder-returning)

**Comment by koskimas** [comment] 2019-11-30 19:29
Fixed in v2.0 branch.

**Closed by koskimas** 2019-11-30 19:29 UTC
Labels: enhancement, good first issue, help wanted, typings
