### ISSUE TITLE
How does ManyToManyRelation work with insert/update in 0.5 ?

### ISSUE THREAD

**Issue by purepear** [Vincit/objection.js#157] opened 2016-06-30 15:28 UTC
I can't figure how to insert/update my record having the ids of the ManyToMany relation.

**Comment by elhigu** [comment] 2016-07-01 11:50
@purepear Could you describe your use case a bit more? 

There are many ways to handle that stuff. Are you talking about `.insertWithRelated` or just `.insert / .update`? For insert / update you might want to use http://vincit.github.io/objection.js/#relate

**Comment by purepear** [comment] 2016-07-08 08:24
Hi, @elhigu 
Let's take the 'Preson and Movies' many to many relationship in the docs example http://vincit.github.io/objection.js/#models

I have a html form for the Person model that have multiple select with movies (id => name). So when i submit the form i get the updated Person fields as well as the movies ids. JSON looks like this:
```javascript
{
  id: 1,
  name: "John",
  movies: [1,5,8]
}
```

So.. what i want is when i .update({...})  it should delete all records in PersonMovie that have personId=1... and then insert the new records [{personId:1, movieId:1}, {personId:1, movieId:5}, {personId:1, movieId:8}] ... (or make diff and delete/insert only the necessary relations in PersonMovie)

Does Objection support this? Cause i didn't find how to do it.
Thanks

**Comment by koskimas** [comment] 2016-07-08 15:02
There is no single method that can achieve this. Have you tried something like this:

```js
let john = Person.fromJson({id: 1});
await john.$relatedQuery('movies').unrelate();
await john.$relatedQuery('movies').relate([1,5,8]);
```

This only works if Person doesn't have required properties in jsonSchema since `fromJson` validates the object. Also `relate` with multiple values only works with postgres.

Another way is to use knex and modify the pivot table directly (this is what I would probably do):

```js
knex('Person_Movie').delete().where('personId', 1);
knex('Person_Movie').insert(_.map([1,5,8], id => ({personId: 1, movieId: id}));
```

**Comment by purepear** [comment] 2016-07-08 15:34
I did the second one a week ago. But i was curious if there's a better way
Thanks @koskimas

**Comment by ersims** [comment] 2016-07-08 17:20
It would be really awesome if it was possible to use [`.relate()`](http://vincit.github.io/objection.js/#relate) the same way as [`.unrelate()`](http://vincit.github.io/objection.js/#unrelate), by using a where clause. It would make it possible to do something like this and still be supported across different databases

```js
let john = Person.fromJson({id: 1});
await john.$relatedQuery('movies').relate().whereIn('id', [1,5,8]);
```

**Comment by koskimas** [comment] 2016-07-08 20:10
`whereIn` would be confusing here since it would't get compiled in to a `WHERE` clause. 

There is a cross-db way to insert multiple rows at once, but the problem is that postgres is the only database that returns the identifiers of all created rows. Other databases just return one id. Now that I think about it, I don't think that is an issue with `relate` since it doesn't return anything. Maybe I could just remove the `isPostgres` check.

**Comment by ersims** [comment] 2016-07-08 21:03
I guess I am trying to say that maybe it should compile into a `WHERE` clause like it does for `unrelate()`. I believe it would feel more consistent. Maybe I am misunderstanding something, but it would be nice to be able to do this when using a non-id column as criteria;

```js
transaction(Account, (Account) => {
    return Account.query()
        .column('id')
        .findById(id)
        .then((account) => {
            return Promise.all([
                account
                    .$relatedQuery('contacts')
                    .unrelate()
                    .whereNotIn('email', listOfEmailAddresses),
                account
                    .$relatedQuery('contacts')
                    .relate()
                    .whereIn('email', listOfEmailAddresses)
            ]);
    });
});
```

instead of
```js
transaction(Account, Contact, (Account, Contact) => {
    return Account.query()
        .column('id')
        .findById(id)
        .then((account) => {
            return Promise.all([
                account
                    .$relatedQuery('contacts')
                    .unrelate()
                    .whereNotIn('email', listOfEmailAddresses),
                Contact.query().column('id').whereIn('email', listOfEmailAddresses)
                    .map((contact) => account.$relatedQuery('contacts').relate(contact.id))
            ]);
    });
});
```

**Comment by koskimas** [comment] 2016-07-29 09:43
Closing this as the original issue was resolved. @ersims feel free to open a new issue for your request.

**Closed by koskimas** 2016-07-29 09:43 UTC
