### ISSUE TITLE
Eagered grandparents disappear when selecting the pkey as an alias on eagered parents

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#403] opened 2017-06-08 19:30 UTC
Hey,
I'm trying to clean out some of my columns when selecting/eagering by using .select() in a modifyEager() (and/or using the syntax with the comma and object full of functions), but if I try to clean out the top level eagered item of random columns, the bottom level doesn't get eagered at all and I can't figure out how to get it back. I've fixed this for now with omit as you'll see below (omitting a bunch of stuff including a json column called object_data and then overriding that with the select to get just the object_data->>name), but I only want page_id and object_data->>'name.' Here's the solution I came to that works, but I'd love for there to be a syntax to do this more naturally. 

Currently what I have: 
```
return await Page
            .query()
            .findById(page_id)
            .eager('[parents.[parents]]')
            .omit(Page, eager.pageDataOmission) // eager.pageDataOmission is a big array of columns I don't want
            .modifyEager('parents.parents', builder => {
                builder.select('page_id', knex.raw("object_data->>'name' as name"))
            })
            .select('page_id', knex.raw("object_data->>'name' as name"));
```
successfully returns...
```
{
            page_id: 5,
            name: "My Page",
            parents: [
                        {
                                    page_id: 6, //though I'd love to rename this column
                                    name: "My Page's Subdomain/Parent"
                                    parents: [
                                                page_id: 7,  //though I'd love to rename this column
                                                name: "My Page's Domain/Grandparent",
                                    ]
                        }, 
                        {...another parent...}
            ]
}
```
I'd love to do this instead, but it deletes the nested parents array from the first set of parents.

```
return await Page
            .query()
            .findById(page_id)
            .eager('[parents.[parents]]')
            .modifyEager('parents, parents.parents', builder => {
                builder.select('page_id', knex.raw("object_data->>'name' as name"), 'parents') // <-- currently "parents" breaks it since that's not a column
            })
            .select('page_id', knex.raw("object_data->>'name' as name"));
```
But this currently results in... 
```
{
            page_id: 5,
            name: "My Page",
            parents: [
                        {
                                    page_id: 6,
                                    name: "My Page's Subdomain/Parent"
                                    ///// no grandparents because I'm only able to select page_id and name ////
                        }, 
                        {...another parent...}
            ]
}
```
Or, though this is longer and more redundant, it allows me to dynamically select from specific layers.
```
return await Page
            .query()
            .findById(page_id)
            .eager('[parents(cleanedUpSubdomains).[parents(cleanedUpDomains]]', {
                        cleanedUpSubdomains: (builder) => {
                            builder.select('page_id as subdomain_id', knex.raw("object_data->>'name' as name")) // currently works, but overrides the below
                        },
                        cleanedUpDomains: (builder) => {
                            builder.select('page_id as domain_id', knex.raw("object_data->>'name' as name"))
                        }
            })
            .select('page_id', knex.raw("object_data->>'name' as name"));
```

Any thoughts?
Thanks,
-Allxie

**Comment by koskimas** [comment] 2017-06-08 19:42
Which objection version are you using?

**Comment by allxie** [comment] 2017-06-08 19:56
0.7.12

**Comment by koskimas** [comment] 2017-06-08 20:03
Damn I really thought this was because use used and ancient version. This should have been fixed in 0.7.4. You should be able to select any columns in named filters or `modifyEager` and the needed relation columns are automatically selected and later removed to make the eager fetching work. I don't know what makes your query special. I'll try to reproduce the bug.

Is `parents` in your example a many-to-many relation or has-many relation?

**Comment by koskimas** [comment] 2017-06-08 20:23
I wrote this test and it works correctly..

```js
    describe.only('Eagered grandparents disappear when adding select clause to parents #403', () => {
      let knex = session.knex;
      let Page;

      before(() => {
        return session.knex.schema
          .dropTableIfExists('page')
          .createTable('page', table => {
            table.integer('id').primary();
            table.integer('page_id');
            table.jsonb('object_data');
          });
      });

      after(() => {
        return session.knex.schema.dropTableIfExists('page');
      });

      before(() => {
        Page = class Page extends Model {
          static get tableName() {
            return 'page';
          }

          static get jsonAttributes() {
            return ['object_data'];
          }

          static get relationMappings() {
            return {
              parents: {
                relation: Model.HasManyRelation,
                modelClass: Page,
                join: {
                  from: 'page.id',
                  to: 'page.page_id'
                }
              }
            };
          }
        };

        Page.knex(session.knex);
      });

      before(() => {
        return Page
          .query()
          .insertGraph({
            id: 1,
            object_data: {name: '1'},

            parents: [{
              id: 2,
              object_data: {name: '1_1'},

              parents: [{
                id: 4,
                object_data: {name: '1_1_1'}
              }, {
                id: 5,
                object_data: {name: '1_1_2"'}
              }]
            }, {
              id: 3,
              object_data: {name: '1_2"'},

              parents: [{
                id: 6,
                object_data: {name: '1_2_1'}
              }, {
                id: 7,
                object_data: {name: '1_2_2"'}
              }]
            }]
          });
      });

      it('test', () => {
        return Page
          .query()
          .findById(1)
          .eager('parents.parents')
          .modifyEager('[parents, parents.parents]', builder => {
            builder.select('page_id', knex.raw("object_data->>'name' as name"));
          })
          .select('page_id', knex.raw("object_data->>'name' as name"))
          .then(pages => {
            console.dir(pages, {depth: 1000});
          });
      });
    });
```

Can you spot what I did differently?

**Comment by koskimas** [comment] 2017-06-08 21:09
Based on your other issue I'm starting to think that `parents` is a many-to-many relation? I could really use the `Page` model so that I don't waste my time testing the wrong things.

**Comment by allxie** [comment] 2017-06-08 21:20
Page is many to many. 
Here's the page model file ~~ has a bunch of crap that you won't need. I'm running these queries using parents and children. 
Thank you so much for your help!!! 

```
import BaseModel from './BaseModel';
import {Model} from 'objection';
import models from './'

export default class Page extends BaseModel {

    static tableName = 'page';
    static className = 'Page';
    static idColumn = 'page_id';

    async $afterGet(context) {
        if (context.addPageableEntity) {
            // After each page row is retrieved --> If context.addPageableEntity is set to true --> find the pageable Entity's Model (ex. Vendor, LegalEntity, etc.) --> fetch the pageable entity and add it to the json
            const pageableEntityModel = models[this.pageable_entity_type]
            this.pageable_entity = pageableEntityModel && await pageableEntityModel.query().where(pageableEntityModel.idColumn, this.pageable_entity_id).first()
        }
    }

    static jsonSchema = {
        type: 'object',
        required: [ 'object_data', 'author_id', 'permissionable_entity_id'],
        // additionalProperties: false,
        properties: {
            page_id: { type: 'integer' },
            commentable_entity_id: {type: ['integer', 'null']},
            documentable_entity_id: {type: ['integer', 'null']},
            permissionable_entity_id: {type: ['integer', 'null']},
            author_id: { type:'integer' },
            pageable_entity_type: { type:'string' },
            modifier_id: { type: 'integer'},
            tagable_entity_id: {type: ['integer', 'null']},
            pageable_entity_id : {type: 'integer'},
            object_data: {
                type: 'object',
                properties: {}
            }
        }
    };


    static relationMappings = {
        author: {
            relation: Model.BelongsToOneRelation,
            modelClass: `${__dirname}/User`,
            join: {
                from: 'page.author_id',
                to: 'user.user_id'
            }
        },
        modifier: {
            relation: Model.BelongsToOneRelation,
            modelClass: `${__dirname}/User`,
            join: {
                from: 'page.modifier_id',
                to: 'user.user_id'
            }
        },
        parents: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            join: {
                from: 'page.page_id',
                through: {
                    from: 'page_relationship.child_id',
                    to: 'page_relationship.parent_id'
                },
                to: 'page.page_id'
            }
        },
        children: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Page`,
            join: {
                from: 'page.page_id',
                through: {
                    from: 'page_relationship.parent_id',
                    to: 'page_relationship.child_id'
                },
                to: 'page.page_id'
            }
        },
        tags: {
            relation: Model.ManyToManyRelation,
            modelClass: `${__dirname}/Tag`,
            join: {
                from: 'page.page_id',
                through: {
                    from: 'page_tag.page_id',
                    to: 'page_tag.tag_id'
                },
                to: 'tag.tag_id'
            }
        },

        commentable_entity: {
            relation: Model.BelongsToOneRelation,
            modelClass: `${__dirname}/CommentableEntity`,
            join: {
                from: 'page.commentable_entity_id',
                to: 'commentable_entity.commentable_entity_id'
            }
        },
        documentable_entity: {
            relation: Model.BelongsToOneRelation,
            modelClass: `${__dirname}/DocumentableEntity`,
            join: {
                from: 'page.documentable_entity_id',
                to: 'documentable_entity.documentable_entity_id'
            }
        },
        documents: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Document`,
            join: {
                from: 'page.documentable_entity_id',
                to: 'document.documentable_entity_id'
            }
        },
        comments: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Comment`,
            join: {
                from: 'page.commentable_entity_id',
                to: 'comment.commentable_entity_id'
            }
        },
        permissionable_entity: {
            relation: Model.BelongsToOneRelation,
            modelClass: `${__dirname}/PermissionableEntity`,
            join: {
                from: 'page.permissionable_entity_id',
                to: 'permissionable_entity.permissionable_entity_id'
            }
        },

        permissions: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Permission`,
            join: {
                from: 'page.permissionable_entity_id',
                to: 'permission.permissionable_entity_id'
            }
        },


        change_log: { // todo - how to create page change log
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Changelog`,
            join: {
                from: 'page.page_id',
                to: 'change_log.page_id'
            }
        },


    };
}
```

And here's the model file for the PageRelationship model...

```
import BaseModel from './BaseModel';
import {Model} from 'objection';

export default class PageRelationship extends BaseModel {
    static tableName = 'page_relationship';
    static idColumn = 'page_relationship_id';

    static jsonSchema = {
        type: 'object',
        //required: ['parent_id', 'child_id'],

        properties: {
            page_relationship_id : {type: 'integer'},
            parent_id : {type: 'integer'},
            child_id: {type: 'integer'}

        }
    };

    static relationMappings = {
        children: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Page`,
            join: {
                from: 'page_relationship.child_id',
                to: 'page.page_id'
            }
        },
        parents: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Page`,
            join: {
                from: 'page_relationship.parent_id',
                to: 'page.page_id'
            }
        }
    };
}
```

**Comment by koskimas** [comment] 2017-06-08 21:23
Thanks! I'll update my tests and see what happens.

**Comment by allxie** [comment] 2017-06-08 21:28
(Incidentally, I'm also having trouble working the new jsonb column update (update a single jsonb field rather than taking out the whole thing, modifying, and putting it back in) that @elhigu implemented in #270 (based on this issue from my coworker and I... #187 ) , so I'm curious if there's a knex version problem or something, given that that issue should have been fixed in 0.7.0. I'm in knex version 0.11.7.

**Comment by koskimas** [comment] 2017-06-08 21:34
I still can't reproduce the bug. I updated my test to have exactly the same tables and relations, but all parents/children appear as they should. This is now my test:

```js
    describe.only('#403 and #404', () => {
      let knex = session.knex;
      let Page;

      before(() => {
        return knex.schema
          .dropTableIfExists('page_relationship')
          .dropTableIfExists('page')
          .createTable('page', table => {
            table.integer('page_id').primary();
            table.jsonb('object_data');
          })
          .createTable('page_relationship', table => {
            table.integer('parent_id').references('page.page_id').index().onDelete('CASCADE');
            table.integer('child_id').references('page.page_id').index().onDelete('CASCADE');
          });
      });

      after(() => {
        return knex.schema
          .dropTableIfExists('page_relationship')
          .dropTableIfExists('page');
      });

      before(() => {
        Page = class Page extends Model {
          static get tableName() {
            return 'page';
          }

          static get idColumn() {
            return 'page_id';
          }

          static get jsonAttributes() {
            return ['object_data'];
          }

          static get relationMappings() {
            return {
              parents: {
                relation: Model.ManyToManyRelation,
                modelClass: Page,
                join: {
                  from: 'page.page_id',
                  through: {
                    from: 'page_relationship.child_id',
                    to: 'page_relationship.parent_id'
                  },
                  to: 'page.page_id'
                }
              },

              children: {
                relation: Model.ManyToManyRelation,
                modelClass: Page,
                join: {
                  from: 'page.page_id',
                  through: {
                    from: 'page_relationship.parent_id',
                    to: 'page_relationship.child_id'
                  },
                  to: 'page.page_id'
                }
              }
            };
          }
        };

        Page.knex(knex);
      });

      before(() => {
        return Page
          .query()
          .insertGraph({
            page_id: 1,
            object_data: {name: '1'},

            parents: [{
              page_id: 2,
              object_data: {name: '1_1'},

              parents: [{
                page_id: 4,
                object_data: {name: '1_1_1'}
              }, {
                page_id: 5,
                object_data: {name: '1_1_2'}
              }]
            }, {
              page_id: 3,
              object_data: {name: '1_2"'},

              parents: [{
                page_id: 6,
                object_data: {name: '1_2_1'}
              }, {
                page_id: 7,
                object_data: {name: '1_2_2'}
              }]
            }]
          });
      });

      it('Eagered grandparents disappear when adding select clause to parents #403', () => {
        return Page
          .query()
          .findById(1)
          .eager('parents.parents')
          .modifyEager('parents', builder => {
            builder.select('page_id', knex.raw("object_data->>'name' as name"));
          })
          .modifyEager('parents.parents', builder => {
            builder.select('page_id', knex.raw("object_data->>'name' as name"));
          })
          .select('page_id', knex.raw("object_data->>'name' as name"))
          .then(pages => {
            console.dir(pages, {depth: 1000});
          });
      });

      it('Select jsonb fields when using .joinRelation #404', () => {
        return Page
          .query()
          .where('page.page_id', 1)
          .leftJoinRelation('parents.parents')
          .select("parents:parents.page_id as page_id", knex.raw(`"parents:parents"."object_data"->>'name' as name`)) 
          .then(pages => {
            console.dir(pages, {depth: 1000});
          });
      });
    });
```

Both of the tests work..

**Comment by koskimas** [comment] 2017-06-08 21:39
I'm testing on 0.8.2 though. There shouldn't be any updates that could affect this, but maybe there is. Can you try out 0.8.2? You seem to be using babel, so you probably need to make some changes to your setup as described here: https://github.com/Vincit/objection.js/issues/388

**Comment by allxie** [comment] 2017-06-08 21:42
Ahah!
Okay, so...this works...

```
return await Page
            .query()
            .findById(page_id)
            .eager('[parents.[parents]]')
            .modifyEager('parents', builder => {
                builder.select('page_id', knex.raw("object_data->>'name' as name")) 
            })
            .modifyEager('parents.parents', builder => {
                builder.select('page_id as domain_id', knex.raw("object_data->>'name' as name"))
            })
            .select('page_id', knex.raw("object_data->>'name' as name"));
```
And this breaks: 
```
return await Page
            .query()
            .findById(page_id)
            .eager('[parents.[parents]]')
            .modifyEager('parents', builder => {
                builder.select('page_id as subdomain_id', knex.raw("object_data->>'name' as name")) // <---- the only difference is the alias
            })
            .modifyEager('parents.parents', builder => {
                builder.select('page_id as domain_id', knex.raw("object_data->>'name' as name"))
            })
            .select('page_id', knex.raw("object_data->>'name' as name"));
```

**Comment by koskimas** [comment] 2017-06-08 21:50
There it is! Objection thinks the needed `page_id` is selected and doesn't explicitly select it. But when it later attempts to used to fetch the related models, it isn't found since it's aliased.

I'll try to fix this, but if the fix requires a huge refactor, I won't probably do it right now since this isn't very common case. In the meantime maybe you can convert the `page_id` into something else in `$formatJson` method? That's the method that maps the data when a model is serialized into json (for example when JSON.stringify is called for it).

**Comment by allxie** [comment] 2017-06-08 21:56
Yes, absolutely. Thanks so much, again, for your help! I got to refactor my code to remove .omit(), which was causing all sorts of other problems.

**Comment by koskimas** [comment] 2017-06-08 22:03
Since you are using a lot of those complex `modifyEager` filters, maybe you would benefit from the new `namedFilters` feature. It allows you to do this:

```js
class Page extends Model {
  ...
  static namedFilters = {
    name: builder => builder.select(knex.raw("object_data->>'name' as name")),
    page_id: builder => builder.select('page_id')
  }
  ...
}
```

return await Page
  .query()
  .findById(page_id)
  .eager('parents(name, page_id).parents(name, page_id)')
  // After next release you can replace the following two lines with
  // .modify('name', 'page_id')
  .modify(Page.namedFilters.name)
  .modify(Page.namedFilter.page_id)

**Comment by allxie** [comment] 2017-06-08 22:12
Oh, amazing! Thanks a lot!

**Comment by newhouse** [comment] 2017-06-09 04:18
Been following along here a bit, and have a question for @koskimas. I'm not that familiar with the `namedFilters` feature yet, but why did you add the two calls to `modify()` to the just-above example? Won't they end up stripping out all but the `page_id` and `object_data-->>'name' as name` from the starting/primary child? Or was it simply to highlight a neat way to apply a `namedFilter` to the primary query (rather than the usual use in `eager` expressions)?

**Comment by koskimas** [comment] 2017-06-09 07:31
@newhouse The modify calls simply apply the filters for the main query also (the original example had the same selects for the main query and for the relations). You don't need to call `modify` for the the name filters to work in the eager expression.

**Comment by newhouse** [comment] 2017-06-09 07:38
Thanks @koskimas !

**Closed** 2017-06-09 09:41 UTC
Labels: bug
