### ISSUE TITLE
Model class unable to implement custom query builder

### ISSUE THREAD

**Issue by juliancoleman** [Vincit/objection.js#813] opened 2018-02-21 21:31 UTC
> `Objection v1.0.0`
> 
> Found by myself and @jadengore,

Let's say I've created a custom query builder with a nice helper method

```ts
export default class CustomQueryBuilder<T> extends QueryBuilder<Model, T> {
  whereLike(column: string, value: string): CustomQueryBuilder<T> {
    return this.whereRaw("lower(??) like '%' || lower(?) | '%'", [column, name]);
  }
}
```

Now, we implement on our base Model

```ts
import CustomQueryBuilder from "./CustomQueryBuilder";

export default class Base extends Model {
  "#id": string;

  static QueryBuilder: CustomQueryBuilder;

  // or...
  // static get QueryBuilder() {
  //   return CustomQueryBuilder;
  // }
}
```

Base gets the following [ts] error

```
Class static side 'typeof Base' incorrectly extends base class static side 'typeof Model'.
  Types of property 'QueryBuilder' are incompatible.
    Type 'typeof CustomQueryBuilder' is not assignable to type 'typeof QueryBuilder'.
      Type 'CustomQueryBuilder<RM | RV>' is not assignable to type 'QueryBuilder<QM, RM, RV>'.
        Types of property 'throwIfNotFound' are incompatible.
          Type '() => QueryBuilder<Model, RM | RV, RM | RV>' is not assignable to type '() => QueryBuilder<QM, RM, RM>'.
            Type 'QueryBuilder<Model, RM | RV, RM | RV>' is not assignable to type 'QueryBuilder<QM, RM, RM>'.
              Type 'Model' is not assignable to type 'QM'.
```

It looks like on the Model class, we have the following, starting on line 437 of `index.d.ts`:

```ts
static query<QM extends Model>(
  this: Constructor<QM>,
  trxOrKnex?: Transaction | knex
): QueryBuilder<QM>;
```

### The Problem, Therein

In implementing this now—whether on the Model itself, or using the knex raw builder—unless `.whereLike` is called first, a `CustomQueryBuilder<T>` will never be returned, only an `Objection.QueryBuilder`. Any additional chained calls to other methods, such as `.select` or `.from` return `Objection.QueryBuilder`s in which `.whereLike` isn't a method of. Because the QueryBuilder is static on the Model class, expecting a type `Objection.QueryBuilder`, TypeScript will actually throw an error for incompatible types.

Either the Model class needs to be a generic or something like a generic, or the QueryBuilder needs better extensibility. When running tests, the code works as advertised, using either of the following

```ts
static QueryBuilder = CustomQueryBuilder;
```

or

```ts
static get QueryBuilder() {
  return CustomQueryBuilder;
}
```

The problem exists with the typings. It seems that there's no way of actually declaring a `QueryBuilder` with a type of anything but an `Objection.QueryBuilder`.

**Comment by koskimas** [comment] 2018-02-21 22:08
Duplicate of #319

**Closed by koskimas** 2018-02-21 22:08 UTC
