### ISSUE TITLE
How to get model (or table) name from ValidationError?

### ISSUE THREAD

**Issue by waveiron** [Vincit/objection.js#1974] opened 2021-01-18 17:02 UTC
When multiple queries fail, column names in error content become ambiguous

`ValidationError: type: should be equal to one of the allowed values`
`ValidationError: status: should be equal to one of the allowed values`

```typescript
 if (e instanceof ValidationError) {
    console.log(Object.keys(e)); // [ 'name', 'type', 'data', 'statusCode' ] <== no model or table name reference here
 }
```

**Comment by koskimas** [comment] 2021-01-23 12:34
There's no way at the moment. I'll look into adding that.

**Comment by devinivy** [comment] 2021-01-23 15:49
When I build-out a base model class for an application, one common customization that I include is adding the model name to `NotFoundError`s as well.  I use the model name to build descriptive HTTP error messages.  Here's what that typically looks like: https://github.com/devinivy/hapipal-realworld-example-app/blob/69e5838132e5d6d41ed15bb45c71cae78f4448e4/lib/models/helpers/index.js#L7-L14

**Comment by koskimas** [comment] 2021-01-24 08:43
This is a duplicate of #1891. Let's move the conversation there.

**Closed by koskimas** 2021-01-24 08:43 UTC
